const months = [
  {
    name: "September",
    guide: "Intro to gym rules and emergency procedures · Physical fitness (aerobic, strength, flexibility, evaluation) · Body awareness · Run and Jump Levels 1–2 · Terry Fox Run",
    pew: "Active Living, Movement Skill Development, Safety, Personal and Social Development",
    equipment: "Cones, poly spots, pinnies, jump ropes, mats, a drum or speaker, clipboards for a simple fitness check",
    fitness: "Baseline: 30-second skip, wall sit or chair hold, sit-and-reach, and a timed shuttle. Record once; do not rank students.",
    notes: "Week 4 can shift to match your school’s Terry Fox day. If the run is outdoors, use Class 15 as the event and Class 16 as a recovery games day.",
    lessons: [
      { w:1,c:1, title:"Gym rules & freeze", focus:"Space, signals, emergency exit", wu:"Jog the line. Freeze on whistle. Teach start/stop, water, bathroom, fire/lockdown line-up.", skill:"Walk the gym: boundaries, safe landing spots, where equipment lives.", game:"Red Light, Green Light — walk, jog, skip. No elimination; movers on red restart.", cd:"Name one gym rule. Stretch calves and hamstrings.", g12:"Short distance, lots of freezes", g34:"Add gallop and slide", g56:"Students take turns as the light" },
      { w:1,c:2, title:"Emergency procedures in motion", focus:"Calm response, listening under movement", wu:"Captain’s Deck: bow, stern, port, starboard, freeze.", skill:"Practice fire-line and ‘quiet gather’ as a game, then reset to play.", game:"Sharks and Dolphins — hoop islands, then “Shark attack!”", cd:"What does a calm freeze look like?", g12:"Walk-tag only", g34:"Jog-tag, 2 sharks", g56:"Add a rescue by high-five" },
      { w:1,c:3, title:"Personal space & body awareness", focus:"What makes me healthy and active?", wu:"Simon Says locomotor + body-part taps.", skill:"Bubble space: walk without popping a neighbour’s bubble. Name heart, lungs, muscles.", game:"Four Corners: Healthy / Active / Rest / Water. Last corner called is home.", cd:"One thing that makes your body ready to play.", g12:"Teacher names corners", g34:"Students shout a reason at the corner", g56:"Students invent a fifth corner" },
      { w:1,c:4, title:"Cooperative first-week closer", focus:"Working together, fair start", wu:"Rikki Tikki: pairs match called body parts.", skill:"Move a hoop or beanbag across the gym as a pair without dropping.", game:"Hot Dog Tag.", cd:"Handshake line. Praise one fair play.", g12:"Beanbags, walking", g34:"Foam balls, jogging", g56:"Add a ‘helper zone’ for balls that stall" },
      { w:2,c:1, title:"Aerobic play", focus:"Heart rate, continuous movement", wu:"Music walk-jog. Hand on heart 10 seconds.", skill:"Teach pulse check at neck or wrist. Easy / medium / hard language.", game:"Hospital Tag. Two tags = stretch hospital, then re-enter.", cd:"Is your heart faster? Why?", g12:"Walk-jog only", g34:"Skip and side-slide rounds", g56:"Students lead the hospital stretch" },
      { w:2,c:2, title:"Strength that kids can do", focus:"Muscular control, name muscle groups", wu:"Animal walks: bear, crab, frog.", skill:"Stations ~4 min: wall push, sit-to-stand, plank on knees, Superman holds. Name arms, legs, core.", game:"Circle Challenge — class holds a shape while one student travels the circle.", cd:"Name the muscle that felt the work.", g12:"Shorter holds", g34:"Add a count out loud", g56:"Peer cue: ‘straight back’" },
      { w:2,c:3, title:"Flexibility & stillness", focus:"Safe stretch, breathing", wu:"Slow walk, then joint circles.", skill:"Teach 20-second stretches: calves, hamstrings, shoulders, butterflies. No bouncing.", game:"Musical Mats — move, freeze in a stretch shape on the spot.", cd:"Child’s pose or seated breathing.", g12:"Copy the teacher shape", g34:"Hold and breathe 3 times", g56:"Lead one stretch for the class" },
      { w:2,c:4, title:"Fitness check (not a race)", focus:"Personal baseline, not ranking", wu:"Easy jog + pulse check.", skill:"Rotate: skip 30s, shuttle, sit-and-reach, wall sit. Teacher records privately.", game:"Clockwise tag in a big circle to finish happy.", cd:"Your body is a starting point, not a scoreboard.", g12:"Play versions, no clipboards in their hands", g34:"Self-count skips", g56:"Set one private goal for October" },
      { w:3,c:1, title:"What makes me healthy?", focus:"Choices, hydration, rest", wu:"Red Light with healthy-choice prompts (sleep, water, play).", skill:"Four-corner talk-move: food that fuels, sleep, outdoor play, screen pause.", game:"Hungry Hippos with foam balls — collect ‘fuel,’ return to nest.", cd:"Name one fuel you can choose this week.", g12:"Pictures at corners", g34:"Students justify the corner", g56:"Debate a tricky example (juice vs water)" },
      { w:3,c:2, title:"Major muscle groups", focus:"Name and move", wu:"Teacher calls a muscle; students show it working.", skill:"Map: calves, quads, hamstrings, core, biceps, shoulders. One action each.", game:"Body-part basketball — tag a called muscle on a partner’s pinnie (soft, no grab).", cd:"Point to three muscles you used.", g12:"Three muscles only", g34:"Six muscles", g56:"Students quiz the class" },
      { w:3,c:3, title:"Hearts and lungs", focus:"Breathing with work", wu:"Walk, jog, skip; notice breath.", skill:"In through nose, out through mouth after a burst. 20-second dash then recover.", game:"Shipwreck / Captain’s Coming with long ‘storm’ jogging rounds.", cd:"Count breaths back to quiet.", g12:"Shorter storms", g34:"Feel pulse after a storm", g56:"Explain why recovery matters" },
      { w:3,c:4, title:"Active for life — class contract", focus:"Personal responsibility", wu:"Partner high-five jog.", skill:"Class writes 5 gym promises on a chart (listen, space, try, kind, tidy).", game:"Students vote the closer: Steal the Bacon or Four Corners.", cd:"Sign the contract with a stretch.", g12:"Teacher scribes", g34:"Pairs suggest a rule", g56:"Students enforce kindly next week" },
      { w:4,c:1, title:"Run Level 1 & 2", focus:"Jogging form, pacing", wu:"High knees, butt kicks, skips.", skill:"Cues: eyes up, quiet feet, arms pump. Fast / slow lanes.", game:"Line Tag / Pac-Man — stay on gym lines.", cd:"Walk, then calf stretch.", g12:"Stay on the wide line", g34:"Add a change-of-speed cue", g56:"Students set a lap goal" },
      { w:4,c:2, title:"Jump Level 1 & 2", focus:"Two-foot takeoff and soft landing", wu:"Jump the river (two ropes).", skill:"Bend–jump–stick. Jump forward, up, and over low objects.", game:"Lily pads: hoop-to-hoop jumps. If you miss, start that path again.", cd:"Why do we bend our knees?", g12:"Low or no objects", g34:"Add a half-turn jump", g56:"Distance challenge with a safe stick" },
      { w:4,c:3, title:"Terry Fox prep", focus:"Pacing, purpose, community", wu:"Story-jog: 30 seconds easy, 15 seconds quicker, repeat.", skill:"Practise the school route or a gym loop. Talk why we run for Terry.", game:"Relay of kindness — tag a teammate with a foam ‘torch.’", cd:"One sentence about courage.", g12:"Walk-run intervals", g34:"Jog most of the loop", g56:"Help younger runners if combined" },
      { w:4,c:4, title:"Terry Fox day or recovery games", focus:"Celebrate effort", wu:"Easy lap in honour of the run.", skill:"If the run already happened: stretch and share. If not: do the school run.", game:"Favourite September games buffet (Red Light, Pac-Man, Clean Your Room).", cd:"Fitness update talk: what got easier this month?", g12:"Choose the calmer game", g34:"Mix two games", g56:"Students host a station" },
    ],
  },
  {
    name: "October",
    guide: "Sending and receiving — kick and throw using different body parts and implements",
    pew: "Movement Skill Development, Movement Tactics, Safety",
    equipment: "Foam balls, beanbags, pinnies, cones/gates, a wall, hoops as targets",
    fitness: "Repeat September shuttle or skip-30s. Note who is more willing to try a new send.",
    notes: "Indoor first. Soccer-style kicking uses foam only. October is kick + underhand throw.",
    lessons: [
      { w:1,c:1, title:"Ready position to receive", focus:"Feet, hands, eyes on the sender", wu:"Self-toss beanbag and catch.", skill:"Partner roll and scoop. Cue: body behind the ball.", game:"Clean Your Room with rolls only.", cd:"Soft hands, bent knees.", g12:"Beanbags", g34:"Foam balls", g56:"Two-ball chaos, still rolls" },
      { w:1,c:2, title:"Underhand throw", focus:"Step with opposite foot, follow through", wu:"Bowler steps across the gym.", skill:"Beanbag to a partner, then to a hoop.", game:"Wall Target Rally — first pair to 7.", cd:"Show the cue without a ball.", g12:"1 metre", g34:"Step back each catch", g56:"Opposite-hand round" },
      { w:1,c:3, title:"Kick a still ball", focus:"Plant foot, laces or inside", wu:"Toe-taps on a foam ball.", skill:"Kick to a partner’s feet. Trap with the sole.", game:"Gate soccer — kick through cones for a point.", cd:"Plant foot beside the ball.", g12:"Walk up to kick", g34:"2-step approach", g56:"Weaker-foot round" },
      { w:1,c:4, title:"Kick and chase", focus:"Send, then move", wu:"Dribble-freeze on whistle.", skill:"Kick, jog after it, trap. Not a blast.", game:"Sharks and Minnows while dribbling foam balls.", cd:"Quiet ball, quiet feet.", g12:"Hands allowed to trap", g34:"Feet only", g56:"Must change direction after each trap" },
      { w:2,c:1, title:"Inside-foot pass", focus:"Accuracy over power", wu:"Partner bump-pass in place.", skill:"Gate passing. Hit 5 gates.", game:"Keep-away 3v1 in a 6-m square (foam).", cd:"Accuracy shout-out.", g12:"3v0 passing", g34:"3v1", g56:"4v2" },
      { w:2,c:2, title:"Throwing to a moving partner", focus:"Lead the receiver", wu:"Jog and self-catch.", skill:"Partner moves along a line; throw to where they will be.", game:"Ultimate-style beanbag: 3 completes to score, no running with it.", cd:"Where did you throw?", g12:"Walk the line", g34:"Jog", g56:"Add a defender" },
      { w:2,c:3, title:"Stop and trap", focus:"Cushion the ball", wu:"Teacher rolls, class traps.", skill:"Sole trap, inside trap, two-hand scoop for younger.", game:"King of the Court trap: stay in if you trap a roll.", cd:"Give with the ball.", g12:"Hands OK", g34:"Feet preferred", g56:"One-touch trap-pass" },
      { w:2,c:4, title:"Kick-throw mix", focus:"Choose the right send", wu:"Teacher calls kick or throw.", skill:"Stations: kick gates, hoop throws, wall toss, partner trap.", game:"Robin’s Nest — feet to collect 3 balls in your hoop.", cd:"Which send felt easier?", g12:"Hands OK", g34:"Feet only", g56:"May steal from other nests" },
      { w:3,c:1, title:"Hitting with an implement", focus:"Safe swing space", wu:"Shadow swings with pool noodles.", skill:"Noodle or short foam bat, tee or teacher toss, hit to a wall.", game:"Noodle baseball — hit, run to a hoop, next batter.", cd:"Two-hand grip, no high follow-through toward people.", g12:"Tee only", g34:"Soft toss", g56:"Opposite-side hits" },
      { w:3,c:2, title:"Hands as implements — bounce pass", focus:"Chest and bounce", wu:"Seated chest-pass.", skill:"Bounce pass to a partner so it arrives at the belly.", game:"Gate passing with bounces.", cd:"Step to the target.", g12:"Roll if bounce is hard", g34:"Bounce only", g56:"Move after you pass" },
      { w:3,c:3, title:"Small-sided kick game", focus:"Space and passing", wu:"Dribble tag.", skill:"3v3 to cone goals, must pass before a shot.", game:"Wall Soccer — 2–3 out, rest are wall goalies, rotate.", cd:"Who passed first?", g12:"No keepers, big goals", g34:"Pass-then-score rule", g56:"One-touch finish allowed" },
      { w:3,c:4, title:"Throwing games day", focus:"Accuracy under a little pressure", wu:"Target toss into hoops.", skill:"Knockdown pins with underhand throws.", game:"Skittles — knock cones, below-waist hits sit 10 then re-enter.", cd:"Soft throws only.", g12:"Tag with beanbags", g34:"Below-waist foam", g56:"Two-ball, still below waist" },
      { w:4,c:1, title:"Sending with different body parts", focus:"Foot, hand, maybe head-height tap", wu:"Body-part send around a circle.", skill:"Thigh volley to self, two-hand bump, kick.", game:"Keep it up as a class with a beach ball.", cd:"Which body part was kindest to the ball?", g12:"Beach ball only", g34:"Add a foam trainer", g56:"Count a class record" },
      { w:4,c:2, title:"Defend the send", focus:"Intercept without contact", wu:"Mirror a partner.", skill:"1v1: attacker sends through a gate, defender shadows.", game:"End-zone beanbag (flag-football style, no contact).", cd:"Hands to yourself.", g12:"No defender, just gates", g34:"Passive defender", g56:"Active intercept" },
      { w:4,c:3, title:"October skill stations", focus:"Quality reps", wu:"Free toss and trap.", skill:"Four stations × ~5 min: kick gates, underhand hoops, bounce pass, noodle hit.", game:"Teacher floats; no extra game.", cd:"Hardest station?", g12:"Helper at each station", g34:"Independent rotate", g56:"Peer cue one skill" },
      { w:4,c:4, title:"Fitness update + favourite send", focus:"Show a skill, stay kind", wu:"Pulse-check jog.", skill:"Quick fitness circuit from September.", game:"Class votes kick game or throw game.", cd:"One skill and one teammate.", g12:"Vote with feet", g34:"Name the cue", g56:"Host the closer" },
    ],
  },
  {
    name: "November",
    guide: "Sending and receiving — catch, stop, hit · Throw Level 1 · Fitness update",
    pew: "Movement Skill Development, Tactics, Character, Safety",
    equipment: "Foam balls, beanbags, scoops or plastic bats, hoops, pinnies, a low net or rope",
    fitness: "Add a throw-for-accuracy station to the monthly update (5 attempts at a hoop).",
    notes: "November finishes the Oct/Nov sending block with catching, stopping, and striking. Throw Level 1 = opposite-foot step, eye on target, follow through.",
    lessons: [
      { w:1,c:1, title:"Catching — ready hands", focus:"Thumbs together above chest, pinkies below", wu:"Self-toss and clap-catch.", skill:"Partner toss 1 m, then back up.", game:"Hot Potato catch around a circle, then two circles.", cd:"Soft hands.", g12:"Beanbag", g34:"Foam ball", g56:"Two-ball tennis" },
      { w:1,c:2, title:"Catch on the move", focus:"Move feet to the ball", wu:"Jog and self-catch.", skill:"Thrower stays; catcher shuffles along a line.", game:"Keep Away with a catchable foam ball, 4v1.", cd:"Feet first, then hands.", g12:"Walk the line", g34:"Shuffle", g56:"Add a second ball" },
      { w:1,c:3, title:"Stop with feet and body", focus:"Get in front, don’t kick at it", wu:"Red Light fielding pose.", skill:"Partner rollers, scoop, toss back.", game:"Grounder Clean Your Room.", cd:"Body in front of the ball.", g12:"Two-hand scoop", g34:"Glove-hand down (barehand OK)", g56:"Backhand attempt" },
      { w:1,c:4, title:"Throw Level 1", focus:"Opposite foot, point at target", wu:"Javelin-walk with a beanbag.", skill:"Wall throws: step, point, follow through. 10 each.", game:"Around-the-world hoop targets.", cd:"Show the cue, no ball.", g12:"Underhand allowed", g34:"Overhand intro", g56:"Opposite-hand set" },
      { w:2,c:1, title:"Hit a tossed ball", focus:"Watch it all the way", wu:"Shadow swings.", skill:"Tee or underhand toss, hit to a wall.", game:"Kickball-style: hit, run to first hoop.", cd:"Contact, then look up.", g12:"Tee", g34:"Toss", g56:"Opposite-side toss" },
      { w:2,c:2, title:"Catching as a team", focus:"Call ‘mine’", wu:"Name-catch in groups of 5.", skill:"Practise a loud ‘I got it’ before the catch.", game:"FLY BACK or Newcomb over a rope.", cd:"Name a good call.", g12:"No rope, just a line", g34:"Rope at reach-height", g56:"Two-touch: catch, set, throw" },
      { w:2,c:3, title:"Stopping a rolling ball in a game", focus:"Field, then throw", wu:"Roll-and-go to a cone.", skill:"Field, pivot, throw to a ‘first base’ hoop.", game:"Beat Ball / Continuous Kick Ball.", cd:"Why throw to the base, not the person?", g12:"Teacher is the thrower", g34:"Student pitcher rolls", g56:"Force play at two hoops" },
      { w:2,c:4, title:"Throw Level 1 under a clock", focus:"Repeatable form", wu:"Arm circles, then 5 easy throws.", skill:"5 throws, walk the cue, 5 more. Quality over distance.", game:"Knockdown the castle (stacked pins).", cd:"Accuracy over smash.", g12:"Underhand pins", g34:"Overhand at 4 m", g56:"Move the line back" },
      { w:3,c:1, title:"Hit with different implements", focus:"Match the tool to the send", wu:"Noodle, scoop, hand — 3 sends.", skill:"Rotate implements at stations.", game:"Station tournament: points for fair hits into a zone.", cd:"Which tool felt safest?", g12:"Noodle and hand", g34:"Add scoop", g56:"Add a short foam bat" },
      { w:3,c:2, title:"Catch-throw rally", focus:"Sustain a rally", wu:"Partner clap-catch.", skill:"How many in a row without a drop?", game:"Class vs. teacher: every pair rallying at once, count drops.", cd:"Reset without blame.", g12:"Beanbag", g34:"Foam", g56:"One-bounce allowed only" },
      { w:3,c:3, title:"Invasion catch game", focus:"Move to space after you throw", wu:"Find-a-spot on the whistle.", skill:"3-second hold, then must pass.", game:"End-zone catch (no running with the ball).", cd:"Where was the open player?", g12:"Walking only", g34:"Jog, 5-second hold", g56:"3-second hold, 1 defender" },
      { w:3,c:4, title:"Striking toward a field", focus:"Fair / foul, running after contact", wu:"Sprint to a called wall.", skill:"Hit, run through first, stop on second (shadow diamond).", game:"Sharks and Minnows with bases as islands.", cd:"Why run through first?", g12:"Two bases only", g34:"Three bases", g56:"Full diamond if space" },
      { w:4,c:1, title:"November stations", focus:"Catch, throw, stop, hit", wu:"Free choice toss.", skill:"Four stations × ~5 min.", game:"Teacher floats.", cd:"Hardest station?", g12:"Adult at hitting station", g34:"Independent", g56:"Peer coaches" },
      { w:4,c:2, title:"Small-sided Newcomb", focus:"Team talk", wu:"Ready position shuffle.", skill:"3-touch catch-throw over a rope.", game:"4-minute games, mix teams.", cd:"Who made a great call?", g12:"Catch and throw only", g34:"Must pass once", g56:"Bump-then-throw optional" },
      { w:4,c:3, title:"Throw Level 1 showcase", focus:"Show the cue", wu:"Partner peer-cue throws.", skill:"Each student demonstrates 3 throws to a hoop.", game:"Team target: hoop scores for the group, not the individual ranking.", cd:"Compliment a form, not a distance.", g12:"Underhand", g34:"Overhand", g56:"Both hands" },
      { w:4,c:4, title:"Fitness update + send buffet", focus:"Apply October–November skills", wu:"Circuit: skip, stretch, 5 throws.", skill:"Quick fitness record.", game:"Vote: Newcomb, kickball, or end-zone catch.", cd:"One skill, one teammate, one goal for December.", g12:"Shorter circuit", g34:"Full circuit", g56:"Students run the vote" },
    ],
  },
  {
    name: "December",
    guide: "Creative movement — tambourine, drum beat, voice (timing and rhythm) · Fitness update",
    pew: "Movement Skill Development, Active Living, Personal and Social Development",
    equipment: "Tambourine or drum, speaker, scarves, ribbons, hoops, mats",
    fitness: "Dance-based pulse check. Note who can start and stop on a beat.",
    notes: "Three weeks to match most Advent calendars. If you have a fourth week, repeat Week 3 with student-built dances.",
    lessons: [
      { w:1,c:1, title:"Start and stop on a beat", focus:"Timing, freeze", wu:"Walk the room to a drum. Freeze on silence.", skill:"Walk, jog, tiptoe matching slow/fast beats.", game:"European Rhythmic Running then musical statues.", cd:"What did your body do on the silent beat?", g12:"Walk and freeze only", g34:"Add skip and slide", g56:"Students take the drum" },
      { w:1,c:2, title:"Levels and shapes", focus:"High, medium, low", wu:"Melt and grow on the drum.", skill:"Shape library: wide, narrow, twisted, round. Hold 3 seconds.", game:"Shape museum — half move, half freeze as statues.", cd:"Name your strongest shape.", g12:"Copy teacher", g34:"Invent a shape", g56:"Linked pair shapes" },
      { w:1,c:3, title:"Voice as the instrument", focus:"Respond to loud, soft, word cues", wu:"Echo claps.", skill:"Move big on loud, small on whisper. Word cues: explode, float, drip.", game:"Story movement: a winter walk the class acts together.", cd:"Breathing after ‘explode.’", g12:"Two cues only", g34:"Four cues", g56:"Student narrators" },
      { w:1,c:4, title:"Partner rhythm", focus:"Match a partner", wu:"Mirror in pairs.", skill:"Clap a 4-beat, then step it, then travel it.", game:"Follow-the-leader trains of 4.", cd:"Thank your partner.", g12:"Teacher claps", g34:"Pairs invent 4 beats", g56:"Switch leaders every 20 seconds" },
      { w:2,c:1, title:"Scarves and pathways", focus:"Pathways: straight, curved, zigzag", wu:"Draw the path in the air.", skill:"Travel your path without colliding.", game:"Traffic scarves — if paths cross, freeze and greet.", cd:"Which path felt smoothest?", g12:"Straight and curved", g34:"Add zigzag", g56:"Draw a path for a classmate" },
      { w:2,c:2, title:"Tambourine phrases", focus:"8-count phrases", wu:"Count 8 while marching.", skill:"4 counts travel, 4 counts shape. Repeat.", game:"Phrase tag: tagged students finish their 8 counts, then sit a turn.", cd:"Can you feel the 8?", g12:"4-count", g34:"8-count", g56:"16-count phrase" },
      { w:2,c:3, title:"Group dance building", focus:"Remember a sequence", wu:"Review phrase from last class.", skill:"Class builds A-B-A: travel, shape, travel.", game:"Perform for the other half, then swap.", cd:"What was hard to remember?", g12:"Teacher-led A-B", g34:"A-B-A", g56:"A-B-A plus a student C" },
      { w:2,c:4, title:"Rhythm games day", focus:"Keep a beat in a game", wu:"Body percussion: stomp-clap.", skill:"Pass a clap around the circle on the beat.", game:"Human Bop-It and Video Game commands.", cd:"Fitness: pulse after the game.", g12:"Slow beat", g34:"Medium", g56:"Syncopated claps" },
      { w:3,c:1, title:"Holiday or winter story dance", focus:"Expression, control", wu:"Shake out, then stillness.", skill:"Three pictures: falling snow, wind, quiet night. Link them.", game:"Whole-class performance to a chosen track or drum.", cd:"Still ending.", g12:"Pictures only", g34:"Link with travel", g56:"Add a group ending shape" },
      { w:3,c:2, title:"Create your own dance", focus:"Student choreography", wu:"Show a move you like.", skill:"Groups of 3–4 build 16 counts.", game:"Share, then mix two groups’ dances.", cd:"Compliment one idea you borrowed.", g12:"Teacher in every group", g34:"16 counts", g56:"32 counts and a formation change" },
      { w:3,c:3, title:"Creative movement stations", focus:"Choice and quality", wu:"Free dance 1 minute.", skill:"Stations: scarves, hoops as frames, drum corner, mirror wall.", game:"Rotate ~5 min.", cd:"Favourite station?", g12:"Two stations", g34:"All four", g56:"Students host" },
      { w:3,c:4, title:"December fitness update + showcase", focus:"Perform and recover", wu:"Easy phrase from the month.", skill:"Short fitness circuit to music.", game:"Class showcase of favourite dances, then a rhythm game.", cd:"One way you kept a beat. Kind body talk.", g12:"Show one shape", g34:"Show a phrase", g56:"MC the showcase" },
    ],
  },
  {
    name: "January",
    guide: "Skating (one day if possible) · Cooperative games · Playground activities · Basketball and floor-hockey skills · Fitness update",
    pew: "Movement Skill Development, Safety, Healthy Relationships, Active Living",
    equipment: "Pinnies, hoops, playground balls, cones, jump ropes, scooters if you have them",
    fitness: "After holidays, redo the September baseline as a ‘welcome back’ check — privately.",
    notes: "If ice time happens, swap any class for a skating lesson: walk-glide, falling safely, two-foot glide, games like Red Light on ice. Otherwise stay in the gym.",
    lessons: [
      { w:1,c:1, title:"Back together — cooperative tag", focus:"Re-enter fairly, no elimination", wu:"Walk-and-wave greet three people.", skill:"Teach ‘tag, freeze, stretch, re-enter.’", game:"Hospital Tag or Hot Dog Tag.", cd:"How did it feel to be unfrozen?", g12:"Walk tag", g34:"Jog", g56:"Two-hand tag only" },
      { w:1,c:2, title:"Partner problems", focus:"Solve a task with one other person", wu:"Back-to-back stand-up.", skill:"Move a hoop from head to floor without hands. Then a beanbag relay.", game:"Pair races that require both people touching the object.", cd:"What words helped?", g12:"Teacher pairs", g34:"Change partners twice", g56:"Silent round" },
      { w:1,c:3, title:"Group of four challenges", focus:"Roles in a small group", wu:"Hula hoop huddle (all hands).", skill:"Blanket/tarp ball carry or four-person hoop walk.", game:"Tripod Tag — 3 join hands, 1 tags, switch roles.", cd:"Name a role you played.", g12:"Walk only", g34:"Jog", g56:"No talking round" },
      { w:1,c:4, title:"Individual challenge inside a group", focus:"Personal best, not vs peers", wu:"Skip or jog at your own pace.", skill:"Station cards: how many can you do well in 40 seconds?", game:"Collective class score (everyone’s reps added).", cd:"Your number is yours.", g12:"Quality over count", g34:"Record privately", g56:"Set a next-week number" },
      { w:2,c:1, title:"Playground: four-square ideas indoors", focus:"Turns, rotation, fair serve", wu:"Bounce-and-catch.", skill:"Teach rotation and ‘friendly serve.’", game:"Four-square with foam, 4 courts if you can.", cd:"What is a fair serve?", g12:"Catch-bounce allowed", g34:"One bounce", g56:"Official rotation" },
      { w:2,c:2, title:"Playground: skipping and hopscotch", focus:"Turn-taking at a rope or grid", wu:"Individual rope or pretend rope.", skill:"Hopscotch grids with tape. Two-foot and one-foot.", game:"Class rotation: rope, hopscotch, wall toss, walk-the-line.", cd:"How do we wait?", g12:"Long rope with teachers turning", g34:"Short rope tries", g56:"Double-dutch intro if safe" },
      { w:2,c:3, title:"Playground: wall and chase games", focus:"Safe outdoor rules indoors", wu:"Wall toss.", skill:"Teach ‘no push-off the wall’ and tag rules.", game:"Wall ball (soft) then Freeze Tag.", cd:"Which playground game needs the most space?", g12:"Wall toss only", g34:"Add one chase game", g56:"Students referee" },
      { w:2,c:4, title:"Skating day or glide games", focus:"Balance and falling safely", wu:"If ice: march in place on skates. If gym: sock-glide or scooter.", skill:"Fall to the side, get up, two-foot glide or scooter push.", game:"Red Light on ice or scooter rivers.", cd:"Safe fall is a skill.", g12:"Walk and glide", g34:"Swizzles or scooter slalom", g56:"Backward walk if ice time" },
      { w:3,c:1, title:"Basketball dribble", focus:"Head up, finger-pads, protect the ball", wu:"Bounce-and-catch on the spot.", skill:"Stationary dribble, then walk-dribble. Cue: pads, not slap. Eyes up at a wall mark.", game:"Rob the Nest — dribble one foam ball at a time.", cd:"Which hand felt easier?", g12:"Two-hand bounce-catch allowed", g34:"Walk-dribble", g56:"Jog-dribble, switch hands" },
      { w:3,c:2, title:"Chest and bounce pass", focus:"Step to the target, catch ready", wu:"Partner toss-catch.", skill:"Chest pass: two hands, step, thumbs down. Bounce pass: hit the floor two-thirds of the way.", game:"Keep Away with a catchable foam ball, 4v1.", cd:"Name a good pass.", g12:"Chest only, short", g34:"Chest and bounce", g56:"Must-pass before a score" },
      { w:3,c:3, title:"Floor hockey — stick safety", focus:"Blade on the floor, no high stick", wu:"Walk with the stick, blade down.", skill:"Push-pass to a partner or gate. Two-hand grip. No slapshots. Foam ball or soft puck.", game:"Numbers Hockey or Through the Gates.", cd:"Where does the blade live?", g12:"Hands on stick, roll a ball if sticks are new", g34:"Push-pass only", g56:"Receive and pass in two touches" },
      { w:3,c:4, title:"Small-sided invasion", focus:"Pass, then move", wu:"Partner pass on the move.", skill:"3v3 or 4v4 on a short court: three completes to score, or a hoop/end-line. No running with the ball.", game:"End-zone catch (no running with the ball).", cd:"Did we look before we sent?", g12:"3v1 keep-away", g34:"3v3 must-pass", g56:"4v4, one extra defender" },
      { w:4,c:1, title:"Whole-class cooperative", focus:"One problem, whole class", wu:"Knots: tangled hands, untangle.", skill:"Move a giant ‘pizza’ (parachute or sheet) without spilling beanbags.", game:"Hungry Snake or parachute popcorn.", cd:"Did we listen?", g12:"Slow waves", g34:"Popcorn beanbags", g56:"Travel the pizza" },
      { w:4,c:2, title:"Inclusion games", focus:"Everyone has a role", wu:"Partner lead-and-follow, eyes closed one at a time (short).", skill:"Jobs: mover, caller, retriever, scorekeeper.", game:"Sitting volleyball or Newcomb so roles rotate.", cd:"Which job did you like?", g12:"Two jobs only", g34:"Four jobs", g56:"Design a job for a classmate who sits today" },
      { w:4,c:3, title:"January stations", focus:"Partner, group, invasion", wu:"Choice warm-up.", skill:"Stations: pair hoop carry, bounce pass, dribble gates, hockey push-pass.", game:"Rotate.", cd:"Favourite station?", g12:"Shorter stations", g34:"Full rotate", g56:"Peer coach one station" },
      { w:4,c:4, title:"Fitness update + game festival", focus:"Play January favourites", wu:"Baseline skip and stretch.", skill:"Quick fitness record — private.", game:"Vote: Keep Away, End-zone catch, or Hospital Tag.", cd:"One cooperative habit to keep in February.", g12:"One game", g34:"Two", g56:"Students run the festival" },
    ],
  },
  {
    name: "February",
    guide: "Skating (one day if possible) · Rope skills · Hoop skills · Fitness update",
    pew: "Movement Skill Development, Active Living, Safety",
    equipment: "Individual ropes, one long rope, hoops (ideally 1 per student), music",
    fitness: "30-second skip is the month’s signature check. Track personal improvement, not class rank.",
    notes: "Jump Rope for Heart can live in May as on the original plan, but February builds the rope skills. Skating remains an optional swap.",
    lessons: [
      { w:1,c:1, title:"Rope safety and rainbow", focus:"Space, turning, no whipping", wu:"Ropes stay on the floor until told. Jog around them.", skill:"Make a rainbow: swing the rope side to side, then over. Cue: turn from the wrists.", game:"Rainbow freeze — rope still on whistle.", cd:"Ropes down before anyone talks.", g12:"Two-hand rainbow", g34:"Over-the-head turn", g56:"Alternate-hand turns" },
      { w:1,c:2, title:"Two-foot jump", focus:"Jump when the rope hits the floor", wu:"Jump in place with no rope, then with a floor rope.", skill:"Self-turned two-foot jumps. Count 1–5.", game:"Jump the river (two long ropes) then individual tries.", cd:"Soft landing.", g12:"Teacher-turned long rope optional", g34:"5 in a row goal", g56:"10 in a row or jog-step" },
      { w:1,c:3, title:"Long rope", focus:"Enter, jump, exit", wu:"Run through a still long rope.", skill:"Teacher-turned rope: in, 1–3 jumps, out.", game:"School: groups wait in a line, cheer the jumper.", cd:"How do we cheer without rushing?", g12:"Run through only", g34:"1–3 jumps", g56:"Students turn for each other" },
      { w:1,c:4, title:"Rope games", focus:"Keep moving if jumping is hard", wu:"Choice: skip or rainbow.", skill:"Helicopters (low), high-low, partner turn for a jumper.", game:"Helicopter: two students sit and swing a rope in a circle on the floor; others jump it.", cd:"Tired wrists stretch.", g12:"Very low helicopter", g34:"Standard", g56:"Add a second rope if space" },
      { w:2,c:1, title:"Hoop — spin and space", focus:"Control, not just hula", wu:"Hoop on the floor, jump in and out.", skill:"Waist spin, arm spin, roll a hoop to a partner.", game:"Chicken Checkers — hoops are rest spots.", cd:"Which spin lasted?", g12:"Arm and floor hoop", g34:"Waist tries", g56:"Change direction spin" },
      { w:2,c:2, title:"Hoop locomotion", focus:"Travel with a hoop", wu:"Step through a hoop like a magic door.", skill:"Skip while rolling, or hoop around one arm while jogging.", game:"Sheepdog: roll hoops home without knocking others.", cd:"Eyes up.", g12:"Carry or roll slowly", g34:"Roll and chase", g56:"Weak-hand roll" },
      { w:2,c:3, title:"Hoop targets and tosses", focus:"Aim", wu:"Toss-catch a hoop to self.", skill:"Hoop toss to a partner, then onto a cone.", game:"Ring toss team scores.", cd:"Soft toss.", g12:"Short distance", g34:"Step back", g56:"Opposite hand" },
      { w:2,c:4, title:"Hoop creative", focus:"Shapes and pathways", wu:"Hoop as a steering wheel.", skill:"Build a body shape inside, on, or through a hoop.", game:"Museum: half pose in hoops, half gallery walk.", cd:"Control beat speed.", g12:"One hoop one shape", g34:"Two linked hoops", g56:"Group sculpture" },
      { w:3,c:1, title:"Rope and hoop stations", focus:"Choice practice", wu:"Free skip or hoop.", skill:"Four stations × ~5 min: two-foot jump, long rope, hoop roll, hoop toss.", game:"Teacher floats.", cd:"Hardest station?", g12:"Adult at long rope", g34:"Independent", g56:"Peer turners" },
      { w:3,c:2, title:"Combine rope + hoop", focus:"Sequence", wu:"Hoop jump then 3 rope jumps.", skill:"Build a 20-second combo.", game:"Show a neighbour, then try theirs.", cd:"Borrow one idea.", g12:"Teacher combo", g34:"20 seconds", g56:"32 seconds with a change of direction" },
      { w:3,c:3, title:"Partner rope", focus:"Turn for someone else", wu:"Partner high-fives.", skill:"One turns, one jumps. Trade.", game:"How many jumps as a pair?", cd:"Kind turning is a skill.", g12:"Long rope with adult", g34:"Short rope pairs", g56:"Both turn a long rope" },
      { w:3,c:4, title:"Skating swap or cardio hoops", focus:"Aerobic play", wu:"If ice: review fall-and-up. If gym: hoop-jog.", skill:"Ice games or hoop relay around cones.", game:"Red Light on ice, or hoop-train tag.", cd:"Pulse check.", g12:"Walk-glide", g34:"Continuous 2 minutes", g56:"Student-led intervals" },
      { w:4,c:1, title:"Rope challenge day", focus:"Personal records", wu:"Easy rainbows.", skill:"Private: how many two-foot jumps without a miss?", game:"Long-rope school plus helicopter.", cd:"Your number stays yours.", g12:"Count attempts, not only jumps", g34:"Best of 3", g56:"Add a criss-cross try" },
      { w:4,c:2, title:"Hoop challenge day", focus:"Personal records", wu:"Spin trials.", skill:"Longest waist spin, farthest fair roll.", game:"Hoop horseshoe + island tag.", cd:"Name a hoop skill that improved.", g12:"Roll for distance", g34:"Spin and roll", g56:"Opposite-hand spin" },
      { w:4,c:3, title:"Big-group rope/hoop games", focus:"Whole class moving", wu:"Music skip.", skill:"Teach one new group game (e.g. snake rope).", game:"Snake, helicopter, hoop islands in rotation.", cd:"Safety: ropes and hoops never thrown at people.", g12:"One game", g34:"Two", g56:"Students rotate hosts" },
      { w:4,c:4, title:"February fitness update", focus:"Skip check + favourite game", wu:"30-second skip (the monthly test).", skill:"Stretch wrists, calves, shoulders.", game:"Vote rope game or hoop game.", cd:"Compare kindly to January — only with yourself.", g12:"March in place if rope is frustrating", g34:"Record skip", g56:"Set a March goal" },
    ],
  },
  {
    name: "March",
    guide: "Parachute games · Circus activities · Fitness update",
    pew: "Personal and Social Development, Movement Skill Development, Safety",
    equipment: "Parachute or large sheet, beanbags, scarves, foam balls, optional unicycle-free circus: plates, feathers, diabolos, benches",
    fitness: "Core and shoulder endurance show up in parachute work — name them.",
    notes: "No parachute? Use a king-size sheet or two blankets. Circus here means balance, toss-and-catch, and showmanship — not aerials.",
    lessons: [
      { w:1,c:1, title:"Parachute ripples and dome", focus:"Together on a count", wu:"Hands on the chute, walk in a circle.", skill:"Small ripples, big waves, mushroom/dome. Cue: lift together.", game:"Dome — step in, sit on the edge, whisper inside.", cd:"Shoulders down.", g12:"Small ripples only at first", g34:"Dome sit", g56:"Students count the lift" },
      { w:1,c:2, title:"Parachute popcorn", focus:"Force and timing", wu:"Ripple review.", skill:"Beanbags on the chute; pop them without losing the chute.", game:"Popcorn: keep 6 bags up. Then colour-pop (only red). ", cd:"Core is working — say so.", g12:"Few bags", g34:"Colour rules", g56:"Pop to a target hoop" },
      { w:1,c:3, title:"Parachute change-places", focus:"Listen for your colour or name", wu:"Walk the circle holding the chute.", skill:"Lift, call two colours, those students change places under the chute.", game:"Sharks and Dolphins with the chute shrinking .", cd:"Heads up when you run under.", g12:"Walk only under", g34:"Jog under", g56:"Three-mouse version" },
      { w:1,c:4, title:"Parachute number games", focus:"Problem-solving as a group", wu:"Numbered spots on the chute if you have them.", skill:"Make a number with bodies on the chute; or ‘all odd colours lift.’", game:"Merry-go-round walk, then freeze numbers.", cd:"Did we wait for everyone?", g12:"Teacher calls", g34:"Student callers", g56:"Silent number shapes" },
      { w:2,c:1, title:"Circus — toss and catch", focus:"Juggle prep, eyes on the object", wu:"Self-toss scarf.", skill:"Scarf, then beanbag, then two scarves. Cue: throw to a window above the head.", game:"Class juggle: how many objects in the air at once?", cd:"Drops are part of circus.", g12:"Scarves", g34:"Beanbag plus scarf", g56:"Two beanbags" },
      { w:2,c:2, title:"Circus — balance", focus:"Stillness on a small base", wu:"Flamingo holds.", skill:"Beanbag on the head, walk a line. Then one-foot on a poly spot.", game:"Museum circus: walk the tight-line (tape), freeze if the bag falls.", cd:"Eyes on a still spot.", g12:"Wide line", g34:"Tape line", g56:"Low bench if you have one, one at a time" },
      { w:2,c:3, title:"Circus — roll and plate", focus:"Object control", wu:"Roll a hoop or ball on a line.", skill:"If you have spin plates or sticks, teach a safe spin. Else: hoop spin on the arm.", game:"Waiter relay: beanbag on a hoop or plate, walk it home.", cd:"Slow is circus-smart.", g12:"Hoop as tray", g34:"Beanbag on a plate", g56:"Turn a corner without a drop" },
      { w:2,c:4, title:"Circus — partner acts", focus:"Trust and timing", wu:"Mirror toss.", skill:"Partner toss 3 in a row. Then a shared balance pose.", game:"Mini acts: 20 seconds, the other half is the audience.", cd:"Applause is the cool-down.", g12:"Teacher in each pair", g34:"20-second act", g56:"30-second act with a bow" },
      { w:3,c:1, title:"Parachute + circus mix", focus:"Whole-class show", wu:"Ripples to music.", skill:"Sequence: dome, popcorn, then a toss-catch around the chute.", game:"Run the sequence twice.", cd:"Name a muscle that worked.", g12:"Two parts", g34:"Three parts", g56:"Students order the sequence" },
      { w:3,c:2, title:"Circus stations", focus:"Practice for the show", wu:"Choice scarf or flamingo.", skill:"Stations: scarves, line-walk, waiter, hoop spin, optional bench.", game:"Rotate ~5 min.", cd:"Wrists and ankles.", g12:"Four stations", g34:"All five", g56:"Peer coaches" },
      { w:3,c:3, title:"Build a circus act", focus:"Begin, middle, end", wu:"Bow practice (serious and silly).", skill:"Groups of 4: 30-second act with a start pose and a still ending.", game:"Rehearse twice.", cd:"Still endings beat messy run-offs.", g12:"Teacher helps structure", g34:"30 seconds", g56:"45 seconds plus a formation change" },
      { w:3,c:4, title:"Circus performance day", focus:"Audience skills", wu:"Quiet walk to ‘seats’ (a line).", skill:"How to watch: eyes on the act, clap at the end.", game:"Each group performs. Then a whole-class parachute finale.", cd:"Compliment a still ending.", g12:"Short acts", g34:"Full acts", g56:"Student MC" },
      { w:4,c:1, title:"Parachute fitness", focus:"Sustained lift", wu:"Walk the chute.", skill:"Timed waves (20s on, 10s off). Name shoulders and core.", game:"Popcorn under fatigue — keep form.", cd:"Why do we rest between lifts?", g12:"Shorter waves", g34:"20/10", g56:"Students time" },
      { w:4,c:2, title:"New parachute games", focus:"Student-created rules", wu:"Favourite ripple.", skill:"Groups invent a chute game with one safety rule.", game:"Play two inventions.", cd:"Fair start shout-out.", g12:"Teacher writes the rule", g34:"One new game", g56:"Two games and a referee" },
      { w:4,c:3, title:"March stations", focus:"Chute or circus choice", wu:"Free scarf.", skill:"Half chute games, half circus stations, then swap.", game:"Teacher floats.", cd:"What do you want in April gymnastics?", g12:"Shorter halves", g34:"Full swap", g56:"Host a station" },
      { w:4,c:4, title:"March fitness update", focus:"Core/shoulder check + favourite", wu:"20s chute lift or plank on knees.", skill:"Sit-and-reach and skip-30s.", game:"Vote parachute or circus closer.", cd:"One skill, one teammate.", g12:"Play check", g34:"Record", g56:"Goal for gymnastics month" },
    ],
  },
  {
    name: "April",
    guide: "Gymnastics · Fitness update",
    pew: "Movement Skill Development, Safety, Character (control over speed)",
    equipment: "Mats, benches (low), hoops, beanbags, wedges if you have them, wall space",
    fitness: "Strength and flexibility are the gymnastics fitness update — stillness is the test.",
    notes: "No inversions that load the neck. Rolls stay on mats. One at a time on benches. Control beats speed all month. Use the Gymnastics checklist page for locomotor, shapes, rolls, and balances.",
    lessons: [
      { w:1,c:1, title:"Shapes: tuck, pike, straddle, stretch", focus:"Strong shapes, tight muscles", wu:"Shake, then freeze in a shape.", skill:"Four shapes on the mat. Hold 3 seconds. Name the shape.", game:"Shape museum.", cd:"Which shape felt strongest?", g12:"Tuck and stretch", g34:"All four", g56:"Add a twist shape" },
      { w:1,c:2, title:"Travel like a gymnast", focus:"Weight transfer, quiet feet", wu:"Animal travels on mats only.", skill:"Bear, crab, seal, bunny hop. Still start and still end.", game:"Traffic animals — change animal on the drum.", cd:"Quiet travel.", g12:"Two animals", g34:"Four", g56:"Students invent a fifth" },
      { w:1,c:3, title:"Balance", focus:"Small base, still eyes", wu:"Flamingo.", skill:"One-foot, scale attempts, beanbag on the head. Relevé if ready.", game:"Who can be a statue through a whole song intro?", cd:"Eyes on one spot.", g12:"Wide base OK", g34:"One-foot 5 seconds", g56:"5–8 seconds plus a change" },
      { w:1,c:4, title:"Jump and land", focus:"Bend–jump–stick", wu:"Jump the river.", skill:"Straight jump, star jump, tuck jump onto mat. Stick the landing.", game:"Lily-pad hoop jumps with a stuck landing.", cd:"Why bend?", g12:"Straight jump only", g34:"Star and tuck", g56:"Half-turn jump" },
      { w:2,c:1, title:"Log roll", focus:"Long, tight body, no head lead", wu:"Rock like a log on the back.", skill:"Log roll across a mat. Stop in a stretch shape.", game:"Log-roll races on mats only — quality over speed.", cd:"Dizzy = sit.", g12:"Teacher spot beside", g34:"Independent", g56:"Two rolls to a shape" },
      { w:2,c:2, title:"Rock and roll (not a neck roll)", focus:"Rock to shoulder-blades, not the head", wu:"Tuck rocks.", skill:"Rock back and up to sit. No diving onto the head.", game:"Rock-and-shape: rock, then freeze a shape.", cd:"Head never leads a collapse.", g12:"Rocks only", g34:"Rock to stand with help", g56:"Rock to stand" },
      { w:2,c:3, title:"Link two skills", focus:"Sequence", wu:"Shape, travel, shape.", skill:"Build: shape + roll or jump + shape.", game:"Pairs teach their link to another pair.", cd:"Share one link you liked.", g12:"Shape + travel", g34:"Three parts", g56:"Four parts with a level change" },
      { w:2,c:4, title:"April stations — travel, jump, roll, balance", focus:"Quality reps", wu:"Mat walk.", skill:"Four stations × ~5 min. Optional low bench walk if one-at-a-time.", game:"Teacher floats.", cd:"Wrists and hips.", g12:"Adult at roll", g34:"Independent", g56:"Peer safety coach" },
      { w:3,c:1, title:"Low apparatus", focus:"Bench walk and step-off", wu:"Line walks on the floor.", skill:"Low bench: walk, stop, step off to a stick on a mat. One at a time.", game:"Waiting students: flamingo or shape holds.", cd:"One at a time is the rule.", g12:"Floor beam (tape)", g34:"Bench with a spotter", g56:"Dip a toe to arabesque attempts" },
      { w:3,c:2, title:"Hoop and mat pathways", focus:"Change of direction with control", wu:"Hoop step-in.", skill:"Path: hoop, mat roll, hoop, stick.", game:"Follow the path in waves of 4.", cd:"Did you rush?", g12:"No roll in the path", g34:"Full path", g56:"Add a jump" },
      { w:3,c:3, title:"Partner balances (simple)", focus:"Base of support, consent", wu:"Stand back-to-back.", skill:"Only counters that both can leave instantly: palm to palm, seated lean.", game:"Statue pairs. No lifts.", cd:"You may say no to a shape.", g12:"Palm to palm only", g34:"Seated lean", g56:"Create a still pair shape" },
      { w:3,c:4, title:"Group sequence", focus:"Unison and canon", wu:"Class stretch shape.", skill:"Whole class: travel, jump, shape on a count.", game:"Perform in canon (waves).", cd:"One thing your group solved.", g12:"Unison only", g34:"Two-wave canon", g56:"Three-wave canon" },
      { w:4,c:1, title:"Build a routine", focus:"Begin, middle, still end", wu:"Favourite shape.", skill:"Individual or pair routine, 20–30 seconds.", game:"Rehearse, then gallery.", cd:"Still ending.", g12:"Two skills", g34:"Four skills", g56:"Six skills plus a level change" },
      { w:4,c:2, title:"Performance and judging kindly", focus:"Character: notice control", wu:"Audience practice.", skill:"Watch for stillness, not tricks.", game:"Perform routines. Class names one controlled moment.", cd:"Compliment a still ending.", g12:"Show one skill", g34:"Full routine", g56:"Student judges use a 3-cue rubric" },
      { w:4,c:3, title:"Gymnastics buffet", focus:"Choice", wu:"Free shapes.", skill:"Open stations from the month.", game:"Students pick two stations, then a class sequence.", cd:"What felt controlled?", g12:"Two stations", g34:"Open gym", g56:"Host" },
      { w:4,c:4, title:"April fitness update", focus:"Strength, flexibility, stillness", wu:"Shape holds 20s.", skill:"Wall sit or chair, sit-and-reach, flamingo time.", game:"Vote a gentle closer: museum or animal relay.", cd:"Control beat speed this month — say why.", g12:"Play versions", g34:"Record", g56:"Goal for May running" },
    ],
  },
  {
    name: "May",
    guide: "Review Level 1 of Run, Jump, Throw · Jump Rope for Heart · Track and field practice · Orienteering (basic) · Fitness update",
    pew: "Active Living, Movement Skill Development, Safety",
    equipment: "Ropes, foam shot or beanbags, cones, hoops, simple maps or picture cards, pinnies",
    fitness: "This is a peak fitness month: skip check plus a timed run. Keep it personal.",
    notes: "Align Jump Rope for Heart with your school’s actual week. Orienteering can be hallway, playground, or gym if the field is wet.",
    lessons: [
      { w:1,c:1, title:"Run review", focus:"Pacing and form", wu:"A-skips, high knees.", skill:"Easy / medium / quick lanes. Eyes up, arms pump.", game:"Buffalo or Line Tag.", cd:"What is a pace you can keep?", g12:"Walk-jog", g34:"Jog a timed minute", g56:"Talk about race pace vs sprint" },
      { w:1,c:2, title:"Jump review", focus:"Takeoff and stick", wu:"Jump the river.", skill:"Standing long jump to a mat. Measure with a ribbon, not a rank.", game:"Lily pads.", cd:"Bend–jump–stick.", g12:"Two-foot only", g34:"Measure privately", g56:"Add a three-step approach if space" },
      { w:1,c:3, title:"Throw review", focus:"Throw Level 1 outdoors if you can", wu:"Arm circles.", skill:"Foam or softball throw for form, then for a zone (not max distance wars).", game:"Zone scoring: 1–2–3 point hoops.", cd:"Opposite foot.", g12:"Underhand zones", g34:"Overhand zones", g56:"Both" },
      { w:1,c:4, title:"Combined run-jump-throw", focus:"Mini triathlon of skills", wu:"Lap + 5 jumps + 5 throws.", skill:"Rotate three stations.", game:"Team points for completed fair attempts, not winners.", cd:"Name your strongest of the three.", g12:"Play stations", g34:"Record attempts", g56:"Peer cue" },
      { w:2,c:1, title:"Rope for Heart — endurance skip", focus:"Keep a rhythm", wu:"Rainbows, then easy jumps.", skill:"30s, rest, 30s. Music on.", game:"Long-rope school.", cd:"Why does the heart like this?", g12:"March or rainbow if needed", g34:"30s bouts", g56:"60s bout" },
      { w:2,c:2, title:"Rope for Heart — games", focus:"Everyone moving for the cause", wu:"Partner turn.", skill:"Helicopter, snake, partner skip.", game:"Jump-in relay: 5 jumps then tag.", cd:"Talk about the Heart & Stroke ‘why’ in one sentence.", g12:"Run through the rope", g34:"5 jumps", g56:"10 jumps or criss-cross tries" },
      { w:2,c:3, title:"JR4H event or practice", focus:"Sustained skipping", wu:"Class photo skip (everyone turning or jumping).", skill:"Stations that match your event.", game:"Continuous skip-or-move for a set song.", cd:"Celebrate effort.", g12:"Choice movement", g34:"Song-length", g56:"Student DJs and timers" },
      { w:2,c:4, title:"From rope back to track", focus:"Legs that can still run", wu:"Easy jog after skip days.", skill:"Build-ups: 20 m easy, 20 m quicker.", game:"Relay baton (foam) around a small track.", cd:"Hand-off is a throw-and-catch skill.", g12:"Walking hand-off", g34:"Jog hand-off", g56:"Changeover box" },
      { w:3,c:1, title:"Sprint starts", focus:"Reaction, not a false start", wu:"Red Light sprints of 10 m.", skill:"Crouch or standing start. Go on a clap.", game:"Reaction races in waves of 4.", cd:"Wait for the signal.", g12:"Standing start", g34:"Three-point", g56:"Crouch intro" },
      { w:3,c:2, title:"Relays", focus:"Baton and lanes", wu:"Hand-off walks.", skill:"Right-to-left hand-off, stay in a cone lane.", game:"Around the Bases Relay or Cone Relay.", cd:"We wait in our lane.", g12:"Beanbag hand-off", g34:"Foam baton", g56:"Upsweep intro" },
      { w:3,c:3, title:"Jumps and throws on the field", focus:"Event practice", wu:"Dynamic legs.", skill:"Long-jump pit or mat; throw zones.", game:"Rotate events in groups of 6.", cd:"Rake / wait / one at a time.", g12:"Mats and foam", g34:"Field if dry", g56:"Official waiting line" },
      { w:3,c:4, title:"Mini meet", focus:"Fair starts, kind spectating", wu:"Spectator practice: how we cheer.", skill:"Three events, everyone does all three.", game:"Ribbon for finishing, not only first.", cd:"Name someone who tried a new event.", g12:"Play meet", g34:"Simple scores", g56:"Student officials" },
      { w:4,c:1, title:"Orienteering — map basics", focus:"Find a control with a picture map", wu:"Walk the gym naming walls.", skill:"Simple map: pictures of cones, doors, trees. Thumb on the map.", game:"Scatter: find 6 picture controls in any order.", cd:"Map stays in your hand.", g12:"3 controls, adult help", g34:"6 controls", g56:"8 controls plus a legend" },
      { w:4,c:2, title:"Orienteering — set course", focus:"Order matters", wu:"Review the map.", skill:"Numbered controls 1–6. Punch or collect a clothespin.", game:"Pairs, stay together.", cd:"What do you do if you are lost? Stop and look.", g12:"Pairs with an adult on the loop", g34:"Pairs", g56:"Solo if the site is fenced" },
      { w:4,c:3, title:"Score-O", focus:"Choose a route", wu:"Point values on controls.", skill:"You have 8 minutes. High-value farther away.", game:"Score-O. Back by the whistle or lose points.", cd:"Did you plan or wander?", g12:"All controls equal", g34:"Score-O 8 min", g56:"Score-O 10 min" },
      { w:4,c:4, title:"May fitness update + field prep", focus:"Run, skip, throw check", wu:"Skip 30s + easy lap.", skill:"Record skip and a timed run (distance that fits your space).", game:"Favourite May game.", cd:"June is track day and T-ball — preview.", g12:"Short timed move", g34:"Record", g56:"Set a meet goal" },
    ],
  },
  {
    name: "June",
    guide: "Track and field activities · T-ball skills — catching, base running, hitting · Fitness update",
    pew: "Movement Skill Development, Tactics, Character, Safety",
    equipment: "Tee or large cone, foam bats, bases or hoops, foam balls, batons, cones",
    fitness: "Last update of the year: celebrate growth from September. No ranking.",
    notes: "Three weeks for most schools. Week 3 is a festival: meet events + T-ball game + year-end fitness talk.",
    lessons: [
      { w:1,c:1, title:"Track meet rehearsal", focus:"Rotate events calmly", wu:"Build-ups.", skill:"Sprint, jump, throw stations as they will run on meet day.", game:"Practice waiting in line as part of the game.", cd:"Officials are helpers.", g12:"Two events", g34:"Three", g56:"Students official one event" },
      { w:1,c:2, title:"Relays and cheering", focus:"Team timing", wu:"Hand-off reviews.", skill:"Full relay in school lanes or cone lanes.", game:"Relay carnival: mixed-age if you have it.", cd:"Cheer the last runner on every team.", g12:"Short legs", g34:"Standard", g56:"Medley (walk-jog-run)" },
      { w:1,c:3, title:"Field events focus", focus:"Safety on jumps and throws", wu:"Dynamic stretch.", skill:"One-at-a-time jump; throws only into a marked sector.", game:"Personal-best attempts, ribbon for a stick landing or a fair throw.", cd:"Wait behind the line.", g12:"Mats and foam", g34:"Field", g56:"Peer rakers / retrievers" },
      { w:1,c:4, title:"Meet day or mini meet", focus:"Do the event, support others", wu:"Class jog together.", skill:"Walk the event order.", game:"The meet.", cd:"What did you notice in someone else?", g12:"Play meet", g34:"School meet", g56:"Lead a younger heat if asked" },
      { w:2,c:1, title:"T-ball toss and catch", focus:"Soft hands, ready position", wu:"Self-toss.", skill:"Partner toss, then flys vs grounders.", game:"Wall Target Rally.", cd:"Body in front.", g12:"Beanbag", g34:"Foam softball", g56:"Move after the catch" },
      { w:2,c:2, title:"Base running", focus:"Through first, stop on second", wu:"Sprint to a called wall.", skill:"Shadow the diamond in waves of 4.", game:"Bases as islands tag.", cd:"Why through first?", g12:"Two bases", g34:"Three", g56:"Full diamond" },
      { w:2,c:3, title:"Hitting off a tee", focus:"Watch the ball, then run", wu:"Shadow swings.", skill:"Tee hits to a wall or field. Then drop the bat in a hoop.", game:"Hit-and-run to first, next batter.", cd:"Bat in the hoop, not thrown.", g12:"Tee, two hands", g34:"Tee plus a toss", g56:"Opposite-side stand" },
      { w:2,c:4, title:"Fielding a grounder to first", focus:"Scoop, pivot, throw", wu:"Partner rollers.", skill:"Field, throw to a hoop at first.", game:"Beat Ball.", cd:"The base is the target.", g12:"Teacher at first", g34:"Student first-base", g56:"Force at two bases" },
      { w:3,c:1, title:"Modified T-ball game", focus:"Everyone bats, everyone fields", wu:"Throw-catch with your batting order.", skill:"Batting order, rotating field spots, no strike-outs: three fair swings then a coach toss.", game:"Continuous Kick Ball or modified T-ball, 4-minute sides.", cd:"What was different from kickball?", g12:"Everyone runs to first only", g34:"Two bases", g56:"Three bases, coach-pitch option" },
      { w:3,c:2, title:"T-ball tactics", focus:"Where to throw, when to run", wu:"Call ‘I got it.’", skill:"If the ball is in front, throw to first. If not, hold.", game:"Small-sided T-ball.", cd:"Name a good ‘I got it.’", g12:"Teacher directs the throw", g34:"Players decide", g56:"Add a cutoff person" },
      { w:3,c:3, title:"Year-end festival", focus:"Choose favourite games from the year", wu:"Student-led warm-up.", skill:"Stations: Hospital Tag, Robin’s Nest, hoop islands, a gymnastic shape, T-ball toss.", game:"Vote the closer: Chuck the Chicken, Continuous Kick Ball, or Captain’s Deck.", cd:"Vote the closer.", g12:"Fewer stations", g34:"All five", g56:"Host" },
      { w:3,c:4, title:"Final fitness update + thank-you", focus:"Growth since September", wu:"Easy lap.", skill:"Repeat September checks privately. Share only if a student wants to.", game:"Handshake game or parachute if you have it.", cd:"One skill, one teammate, one way you will stay active in summer. Optional: our bodies are a gift — we take care of them.", g12:"Draw a favourite game", g34:"Write one goal", g56:"Lead the thank-you line" },
    ],
  },
];


const MONTH_GAMES = {
  September: [
    ["Hospital Tag", "", "Everyone is it. Cover the tag with a hand. Third tag = stretch hospital, then re-enter. 5 min max as a warm-up."],
    ["Hot Dog Tag", "", "Tagged player is the wiener and calls for a bun. Two classmates stand either side, all three shout, then 5-second free."],
    ["Line Tag / Pac-Man", "", "Stay on gym lines. No jumping lines. Use as the run-skill game."],
    ["Sharks and Dolphins", "", "Hoop islands. On “Shark attack!” taggers enter. Take one hoop away each round. No sitting out — extra sharks."],
    ["Captain’s Deck / Shipwreck", "", "Command game: bow, stern, port, starboard, hit the deck, attention. Skip elimination — last group does 5 jumping jacks and stays in."],
    ["Switch", "", "Four corners, one in the middle. On “Switch,” steal a corner. No pushing; first foot on the spot keeps it."],
    ["Rikki Tikki", "", "Pairs race to the middle and match called body parts. Last pair does jumping jacks next round — still playing."],
    ["Frozen Tag", "", "Arms out when frozen. One high-five frees. Keep 2–3 taggers."],
    ["Buffalo", "", "Pairs on inside/outside track, opposite ways. Music on = jog. Music off = meet and sit back-to-back. Last pair leads the next stretch."],
    ["Laps and Lines / Signals", "", "Change locomotor or level on the whistle. Daily September instant activity."],
  ],
  October: [
    ["Robin’s Nest", "", "Four hoop nests, balls in the middle. Feet only. Steal from the middle or another nest. First to 3."],
    ["Wall Soccer", "", "2–3 field players per team; everyone else is a wall-goalie. Rotate every 2–3 minutes."],
    ["Team Tag", "", "Tag team may only tag with a held ball. No throw, no walking with the ball. Tagged players join the tag team."],
    ["Chuck the Chicken", "", "Throw the chicken, run laps around your huddle while the other team lines up and passes over-under."],
    ["Skittles", "", "Knock the other team’s cone-skittles. Hits below the waist sit 10 steamboats, then back in. One fetcher in the safe zone."],
    ["End Zone Ball", "", "Roll (not throw) to your end-zone catchers. Other team intercepts. Soft foam only."],
    ["Card Sharks", "", "Relay: beanbag into a hoop to claim a card. Accuracy over speed."],
    ["Booger Ball", "", "G5–6 invasion: tag the ball-carrier, they must pass, cannot shoot on the tag. Net = 1, hoop = 2."],
  ],
  November: [
    ["FLY BACK", "", "Cross, grab a foam disc or ball from the safe zone, throw it home. Caught = collected. Dropped = goes back."],
    ["Bucket Ball", "", "Pass-only; ball-carrier frozen. Score by a catch in the bucket/on the bench. Rotate the catcher."],
    ["Continuous Kick Ball", "", "Kick off a saucer cone. Partner on the other team replaces the ball to stop the play. Multiple runners."],
    ["Chuck the Chicken", "", "Same as October — now a throwing-accuracy closer."],
    ["Beat Ball / Beat the Ball", "", "Throw or kick, run the bases while fielders throw around the horn."],
    ["Thunderball", "", "Hit or kick through cone rows for 1–2–3 points. Defence stops it before the next row."],
    ["Clothespin Tag", "", "Steal one pin at a time from backs. Kneel to clip a stolen pin on the front (safe). Front pins stay."],
  ],
  December: [
    ["European Rhythmic Running", "", "Locomotor changes on a drum, tambourine, or chanted 8-count."],
    ["Human Bop-It", "", "Kick it, twist it, spin it, pull it, bop it — on the beat."],
    ["Video Game", "", "Play, rewind, fast-forward, pause, eject, slow-motion."],
    ["Captain’s Deck", "", "Same commands as September, now with dance levels and shapes."],
    ["Slap Rover", "", "Call a name over, slap-hand choose, chase back to the line. Use as a rhythm/style walk."],
    ["Mass Challenges", "", "Whole class: 3 slides left, jump high, freeze in a shape. End with a clap."],
    ["Magic Numbers", "", "10-10-10 or 7-7-7 of three named movements."],
  ],
  January: [
    ["Hot Dog Tag", "", "Cooperative unfreeze. Default January tag."],
    ["Blob Tag", "", "Start with one pair linked. Tagged players join. Break blobs at 4 if the chain gets dangerous."],
    ["Tripod Tag", "", "Groups of 4: three join hands, one tags. Short rounds, switch the tagger."],
    ["Bug Tag / Dead Ant", "", "Tagged player is a bug on their back. Four classmates carry by wrists/ankles to a hoop hospital. No lifting off the ground for G1–2 — walk-escort instead."],
    ["Chicken Checkers", "", "2–4 tag pairs. Rest stand in hoops. Step in, say the name, swap. Keep people moving."],
    ["Four Corner Flags", "", "Four teams steal beanbag flags. Safe in your quadrant. No puppy-guarding the hoop."],
    ["Stones", "", "Two-team capture the beanbags. Tagged sit; a teammate links and walks you home."],
    ["Elves, Giants, Wizards", "", "Team RPS: elf beats wizard, wizard beats giant, giant beats elf. Winners chase; tagged join. No elimination."],
    ["Rescue Relay", "", "Run across, take a teammate by the hand, bring them home."],
    ["Hungry Snake", "", "Whole team stays linked. Head picks up objects, passes them back to the bag."],
    ["Keep Away", "", "4v1 or 3v1. Three completes, then switch the middle player."],
    ["End Zone Ball", "", "No running with the ball. Three completes or a catch in the end zone."],
    ["Rob the Nest (dribble)", "", "Dribble or carry one foam ball at a time back to a hoop nest."],
  ],
  February: [
    ["Chicken Checkers", "", "Hoop rest-spots during rope/hoop cardio."],
    ["Sharks and Dolphins", "", "Hoop islands after hoop-skill practice."],
    ["Switch", "", "Fast feet, hoop or poly-spot corners."],
    ["Helicopter / Snake rope", "", "Low long-rope circle. Jump or step over. G1–2: walk the snake."],
    ["Buzz Off / hoop free zones", "", "Hoops are rest. New player says “Buzz off” to take the hoop."],
    ["Rubber Band", "", "Face out from a circle, travel on signal, sprint back on the second signal."],
  ],
  March: [
    ["Sharks and Dolphins (chute)", "", "Parachute shrinks each round instead of removing hoops."],
    ["Bug Tag / Dead Ant", "", "Carry-to-hospital — circus-strong teamwork. G1–2 walk-escort."],
    ["Object Toss mixer", "", "Say a name, toss a scarf. Add objects until several are in the air."],
    ["Pip, Squeak and Wilbur", "", "Trios. Called name runs the circle, through a teammate arch, to a centre beanbag."],
    ["Mr. Clean", "", "Get rid of your two clothespins by clipping them on someone else’s back. Check in the clean hoop."],
    ["Parachute popcorn / dome / cat-and-mouse", "", "Core chute set from the month’s lessons."],
  ],
  April: [
    ["Signals / shapes", "", "Whistle changes level or shape. Gymnastics language: tuck, pike, stretch."],
    ["Body-part beanbags", "", "Move around spots. Called body part must touch the spot."],
    ["Magic Numbers", "", "3 movements × 7, done as travel-jump-shape."],
    ["Daytime / Nighttime", "", "Night = freeze in a gymnastic statue."],
    ["Switch", "", "Corners are mats. Quiet feet only."],
  ],
  May: [
    ["Buffalo", "", "Track intervals with a partner meet-up."],
    ["Around the Bases Relay", "", "Teams at each base, run the diamond."],
    ["Cone Relay", "", "Teacher calls 2-4-3-1; run the cones in that order."],
    ["Memory Relay", "", "Peek at a card pattern behind a bench, rebuild it at home."],
    ["Card Sharks", "", "Throw a beanbag to a hoop to collect a card — throw review."],
    ["Aces", "", "Outdoor if you can. Active war with a card master hoop. G5–6."],
    ["Four Corner Flags", "", "Orienteering-style steal with a map-optional outdoor version."],
    ["Attention Relay", "", "Numbered files. Call a number; those runners loop their team."],
  ],
  June: [
    ["Continuous Kick Ball", "", "T-ball cousin. Kick off a cone; partner replaces the ball to freeze runners."],
    ["Beat Ball", "", "Runner vs the ball around the horn."],
    ["RPS Rounders", "", "Meet in the middle, rock-paper-scissors, winner keeps the ball toward the end zone."],
    ["Thunderball", "", "Hit/kick through point-rows of cones."],
    ["Team Bowling", "", "Bowl at your own line of pins. Fetch and go again."],
    ["Barkball", "", "Hit, run to the end line, fielders tag with the ball in hand."],
    ["Chuck the Chicken", "", "Festival closer."],
    ["Squirrel’s Tail", "", "Tails + nuts in the middle. Steal a nut or a tail. Buy a tail back with two nuts. Outdoor G3–6."],
  ],
};


const GLANCE = [
  ["September", "Rules, emergency, fitness, body awareness, run/jump, Terry Fox", "16 lessons"],
  ["October", "Sending & receiving: kick / throw", "16 lessons"],
  ["November", "Catch / stop / hit · Throw Level 1", "16 lessons"],
  ["December", "Creative movement, rhythm", "12 lessons"],
  ["January", "Skating · cooperative · playground · invent games", "16 lessons"],
  ["February", "Rope skills · hoop skills · skating", "16 lessons"],
  ["March", "Parachute · circus", "16 lessons"],
  ["April", "Gymnastics", "16 lessons"],
  ["May", "Run/jump/throw · JR4H · track · orienteering", "16 lessons"],
  ["June", "Track & field · T-ball", "12 lessons"]
];
if (typeof window !== "undefined") {
  window.PE = { months, MONTH_GAMES, GLANCE };
}
if (typeof module !== "undefined") module.exports = { months, MONTH_GAMES, GLANCE };
