const months = [
  {
    name: "September",
    guide: "Soccer — dribble, trap, pass, shoot · Gym routines in Week 1",
    pew: "Movement Skill Development, Safety, Active Living, Healthy Relationships",
    equipment: "Foam soccer balls, cones/gates, pinnies, hoops",
    fitness: "Pulse check after a dribble game. Private skip or shuttle once late in the month.",
    notes: "Foam only. No slide tackles. Week 1 still teaches freeze and space. Shift one class if your Terry Fox day falls this month.",
    lessons: [
      { w:1,c:1, title:"Gym freeze + soccer space", focus:"Signals, boundaries, no kicking people", wu:"Jog the line. Freeze on the whistle.", skill:"Walk the gym: walls, gates, where balls live. No kicking until the skill.", game:"Red Light with a foam ball at your feet — freeze means trap.", cd:"Name one gym rule and one soccer rule.", g12:"Walk-dribble", g34:"Jog-dribble", g56:"Students take turns as the light" },
      { w:1,c:2, title:"Toe-taps and sole trap", focus:"Ball stays close", wu:"Toe-taps on a still ball.", skill:"Sole trap a roll. Inside-foot tap in place.", game:"Hospital Tag while dribbling — two tags = stretch, then back in.", cd:"Quiet ball, quiet feet.", g12:"Hands may help the trap", g34:"Feet only", g56:"Change direction after each trap" },
      { w:1,c:3, title:"Dribble through gates", focus:"Small touches, head up", wu:"Dribble-freeze.", skill:"Zig-zag cones. Soft touches. Eyes on a wall mark.", game:"Soccer weave relay or Through the Gates.", cd:"Which foot did more work?", g12:"Wide gates", g34:"Standard", g56:"Weaker foot home" },
      { w:1,c:4, title:"Fair-play soccer closer", focus:"Soft tag, everyone in", wu:"Partner high-five jog.", skill:"Class soccer promises: foam, below the knee, no slide.", game:"Sharks and Minnows while dribbling.", cd:"Handshake line.", g12:"Walk", g34:"Jog", g56:"Add a rescue high-five" },
      { w:2,c:1, title:"Inside-foot pass", focus:"Accuracy over power", wu:"Partner bump-pass.", skill:"Gate passing. Plant foot beside the ball.", game:"Keep-away 3v1 in a small square.", cd:"Accuracy shout-out.", g12:"3v0", g34:"3v1", g56:"4v2" },
      { w:2,c:2, title:"Move after you pass", focus:"Send, then find space", wu:"Jog and self-tap.", skill:"Pass, then take three steps to a new cone.", game:"Rob the Nest — feet only, one ball at a time.", cd:"Did you stand still after the pass?", g12:"Hands OK to collect", g34:"Feet only", g56:"May steal from other nests" },
      { w:2,c:3, title:"Receive a moving ball", focus:"Cushion, then send", wu:"Teacher rolls, class traps.", skill:"Trap a partner pass, then return through a gate.", game:"King of the Court trap — stay in if you trap.", cd:"Give with the ball.", g12:"Hands OK", g34:"Feet preferred", g56:"One-touch trap-pass" },
      { w:2,c:4, title:"2v1 to a gate", focus:"Simple tactic", wu:"Dribble tag.", skill:"Two attackers, one shadow defender. Pass before the gate.", game:"End-zone soccer — three passes to score.", cd:"Hands to yourself.", g12:"No defender", g34:"Passive defender", g56:"Active intercept" },
      { w:3,c:1, title:"Shoot to a target", focus:"Plant, follow through low", wu:"Toe-taps, then a still-ball kick to a wall.", skill:"Cone-goal shooting. One kick, then fetch from the side.", game:"Tunnel kick knockdown.", cd:"Fetch from the side.", g12:"Kick from a line", g34:"Two-step approach", g56:"Weaker foot" },
      { w:3,c:2, title:"Shoot after a dribble", focus:"Control, then finish", wu:"Weave to a cone.", skill:"Dribble, trap, shoot. No blast from mid-gym.", game:"Wall Soccer — rotate wall-goalies.", cd:"Who trapped first?", g12:"Big goals, no keepers", g34:"Pass-then-score", g56:"One-touch finish" },
      { w:3,c:3, title:"Small-sided soccer", focus:"Space and passing", wu:"Dribble freeze.", skill:"3v3 to cone goals. Must pass before a shot.", game:"Two games of 3v3, rest are sideline bumpers.", cd:"Who found a teammate?", g12:"4v0 passing", g34:"3v3", g56:"4v4, two touches" },
      { w:3,c:4, title:"Soccer games day", focus:"Apply the month", wu:"Free dribble.", skill:"Class votes: Rob the Nest, Gate soccer, or Sharks.", game:"Chosen game, then a second short game.", cd:"One fair-play moment.", g12:"Walk versions", g34:"Jog", g56:"Student referees" },
      { w:4,c:1, title:"Weaker-foot day", focus:"Both feet", wu:"Left-foot toe-taps.", skill:"Gates and shots with the non-dominant foot.", game:"Opposite-foot weave relay.", cd:"Which foot felt new?", g12:"Either foot", g34:"Non-dominant preferred", g56:"Non-dominant only" },
      { w:4,c:2, title:"Defend without contact", focus:"Shadow, intercept", wu:"Mirror a partner.", skill:"1v1 to a gate. Defender stays an arm away.", game:"Numbers soccer — call a number to enter.", cd:"Hands stay down.", g12:"No contact, wide gate", g34:"Passive", g56:"Active intercept" },
      { w:4,c:3, title:"September soccer stations", focus:"Quality reps", wu:"Free trap.", skill:"Stations: gates, wall pass, target shot, 2v1.", game:"Teacher floats.", cd:"Hardest station?", g12:"Adult at shooting", g34:"Independent", g56:"Peer cue" },
      { w:4,c:4, title:"Festival or Terry Fox swap", focus:"Celebrate effort", wu:"Easy lap.", skill:"If Terry Fox is this week, use this class for the run. If not: soccer buffet.", game:"Favourite September soccer games.", cd:"What got easier?", g12:"Calmer game", g34:"Two games", g56:"Students host" },
    ],
  },
  {
    name: "October",
    guide: "Football — hike, catch, throw, flag, end-zone",
    pew: "Movement Skill Development, Movement Tactics, Safety, Healthy Relationships",
    equipment: "Foam footballs, beanbags, flag belts or pinnies as tails, cones, hoops",
    fitness: "Shuttle or a timed catch-throw. Personal, not ranked.",
    notes: "Foam footballs only. Two-hand touch or flags — no tackling. End-zone games stay no-contact.",
    lessons: [
      { w:1,c:1, title:"Hold and hike", focus:"Grip, hike between the feet", wu:"Jog with a foam football hugged in.", skill:"Centre hikes to a quarterback. Soft toss back.", game:"Steal the Bacon with a foam football.", cd:"Two hands on the ball.", g12:"Beanbag hike", g34:"Foam football", g56:"Hike on a clap" },
      { w:1,c:2, title:"Catch a soft toss", focus:"Ready hands, eyes on the ball", wu:"Self-toss and catch.", skill:"Partner underhand, then a short spiral if it stays soft.", game:"Throw-clap-catch relay.", cd:"Thumbs together above the chest.", g12:"Underhand only", g34:"Add a step-back", g56:"Opposite hand" },
      { w:1,c:3, title:"Overarm throw", focus:"Opposite-foot step", wu:"Javelin steps without a ball.", skill:"Throw to a hoop, then to a partner. Point the non-throwing hand.", game:"Hoop underhand relay, then overarm to the same hoop.", cd:"Step to the target.", g12:"Short throw", g34:"Step back each catch", g56:"Lead the receiver" },
      { w:1,c:4, title:"Move to the catch", focus:"Hands ready while jogging", wu:"Jog and self-catch.", skill:"Partner runs a straight line; throw to where they will be.", game:"Ultimate-style beanbag: three completes to score.", cd:"Where did you throw?", g12:"Walk the route", g34:"Jog", g56:"Add a shadow" },
      { w:2,c:1, title:"Flag or two-hand touch", focus:"Safe tag", wu:"Tail Tag with pinnies.", skill:"Teach flag pull or two-hand touch. Tags stay soft.", game:"Tail Thief — collect, then give tails back.", cd:"No grabbing shirts.", g12:"Walk", g34:"Jog", g56:"Two-hand touch only" },
      { w:2,c:2, title:"Routes: go, out, curl", focus:"Change of direction", wu:"Cone cuts.", skill:"Three routes. Quarterback points, then throws.", game:"Numbers football — called numbers run a route.", cd:"Plant and cut.", g12:"One route", g34:"Three routes", g56:"Audible at the line" },
      { w:2,c:3, title:"End-zone catch", focus:"Score by catching in a hoop zone", wu:"Partner toss into a hoop.", skill:"3v1: two receivers, one QB, one shadow.", game:"End-zone catch — no running with the ball.", cd:"Hands to yourself.", g12:"No defender", g34:"Passive", g56:"Active intercept" },
      { w:2,c:4, title:"Football games day", focus:"Apply the week", wu:"Hike and toss.", skill:"Vote: Steal the Bacon, End-zone, or Around-the-gym.", game:"Chosen game.", cd:"One kind tag.", g12:"Walk", g34:"Jog", g56:"Student QBs" },
      { w:3,c:1, title:"Pitch and hand-off", focus:"Soft give, then run", wu:"Partner hand-off walk.", skill:"QB hands to a runner who goes to a hoop.", game:"Gauntlet run — foam at feet, not a tackle.", cd:"Give, don’t throw at the runner.", g12:"Walk hand-off", g34:"Jog", g56:"Add a flag pull" },
      { w:3,c:2, title:"Defend the passing lane", focus:"Intercept without contact", wu:"Mirror cuts.", skill:"Defender stays between receiver and ball.", game:"Protect the King with a foam football.", cd:"Head up.", g12:"Shadow only", g34:"Contest the catch", g56:"Tip and catch" },
      { w:3,c:3, title:"Small-sided flag", focus:"Hike, pass, score", wu:"Warm routes.", skill:"4v4 to two end-zones. Two-hand touch. Five seconds to throw.", game:"Reset after a score. Everyone plays.", cd:"No tackle talk.", g12:"3v3, no rush", g34:"4v4", g56:"5v5, one rush after a count" },
      { w:3,c:4, title:"Jail-catch football", focus:"Bring a teammate back", wu:"Partner catch.", skill:"Hit by a foam ball below the waist = jail. A catch from a teammate brings you in.", game:"Jail-catch from the Dodgeball page, footballs only.", cd:"Walk the sideline home.", g12:"Teacher toss to jail", g34:"Teammate toss", g56:"Two feet in jail" },
      { w:4,c:1, title:"Opposite-hand throw", focus:"Level the field", wu:"Non-dominant toss.", skill:"Hoop targets with the other hand.", game:"Opposite-hand foam game.", cd:"Laugh and try again.", g12:"Either hand", g34:"Non-dominant", g56:"Non-dominant only" },
      { w:4,c:2, title:"Team talk", focus:"Call mine, call hike", wu:"Circle hike.", skill:"Receivers call ‘mine.’ QB calls a colour route.", game:"Four Corner Flags.", cd:"Kind voices.", g12:"Teacher calls", g34:"Player calls", g56:"Audibles" },
      { w:4,c:3, title:"October stations", focus:"Hike, throw, catch, flag", wu:"Free toss.", skill:"Stations: hike, hoop throw, route, flag pull.", game:"Teacher floats.", cd:"Hardest station?", g12:"Adult at throw", g34:"Independent", g56:"Peer QB" },
      { w:4,c:4, title:"October festival", focus:"Celebrate the month", wu:"Easy routes.", skill:"Buffet of end-zone, flags, and Steal the Bacon.", game:"Fitness talk: a throw that improved.", cd:"Thank a teammate.", g12:"One game", g34:"Two games", g56:"Students host" },
    ],
  },
  {
    name: "November",
    guide: "Basketball — dribble, pass, shoot, small-sided games",
    pew: "Movement Skill Development, Movement Tactics, Safety, Active Living",
    equipment: "Foam basketballs, hoops or buckets, pinnies, cones",
    fitness: "30-second dribble or wall-pass count. Private.",
    notes: "Finger-pads, not a slap. Balls stay below the waist in the gym. No benches to stand on for shooting.",
    lessons: [
      { w:1,c:1, title:"Finger-pad dribble", focus:"Ball below the waist, head up", wu:"Stationary dribble, switch hands.", skill:"Walk-dribble. Eyes on a wall mark.", game:"Dribble the gates.", cd:"Pads, not a slap.", g12:"Two-hand bounce-catch OK", g34:"Walk-dribble", g56:"Jog; switch at the turn" },
      { w:1,c:2, title:"Protect the dribble", focus:"Body between ball and shadow", wu:"Dribble-freeze.", skill:"1v1 shadow — defender may not touch.", game:"Rob the Nest — dribble one ball at a time.", cd:"Head up.", g12:"No shadow", g34:"Passive", g56:"Active shadow" },
      { w:1,c:3, title:"Chest pass", focus:"Thumbs down, step to the target", wu:"Seated chest-pass.", skill:"Partner pass, then wall chest-pass.", game:"Wall chest-pass relay.", cd:"Step and push.", g12:"Catch-bounce OK", g34:"Clean catch", g56:"Move after you pass" },
      { w:1,c:4, title:"Bounce pass", focus:"Hit the floor halfway", wu:"Seated bounce.", skill:"Pass so it arrives at the belly.", game:"Gate bounce-pass.", cd:"Step to the target.", g12:"Roll if needed", g34:"Bounce only", g56:"Pass and cut" },
      { w:2,c:1, title:"Shoot to a hoop or bucket", focus:"Bend, push, follow through", wu:"Form without a ball.", skill:"Shoot into a hoop or bucket on the floor, then a wall target.", game:"Weave in and out then shoot (relay).", cd:"Soft landing after the shot.", g12:"Two-hand push", g34:"One-hand set", g56:"Jump-stop then shoot" },
      { w:2,c:2, title:"Dribble then shoot", focus:"Stop under control", wu:"Dribble to a cone.", skill:"Jump-stop, then shoot. No travel.", game:"Pin dodgeball if you need a send game; else target relay.", cd:"Feet set before the shot.", g12:"Walk-dribble shoot", g34:"Jog", g56:"Weaker hand dribble" },
      { w:2,c:3, title:"Give and go", focus:"Pass, then move", wu:"Partner pass and walk.", skill:"Pass, cut to a hoop, receive.", game:"3v1 keep-away, then a shot.", cd:"Don’t stand after the pass.", g12:"No defender", g34:"Passive", g56:"Active" },
      { w:2,c:4, title:"Basketball games day", focus:"Apply the week", wu:"Free dribble.", skill:"Vote: Rob the Nest, gates, or wall-pass.", game:"Chosen game.", cd:"One assist you noticed.", g12:"Walk", g34:"Jog", g56:"Student coaches" },
      { w:3,c:1, title:"Triple threat and pivot", focus:"Meet the ball, then decide", wu:"Catch and freeze.", skill:"Pivot front and reverse. No travel.", game:"Everybody’s It as a warm closer if time.", cd:"Ball in both hands on the pivot.", g12:"Pivot only", g34:"Add a pass", g56:"Add a shot" },
      { w:3,c:2, title:"Defend without reaching", focus:"Slide, hands up", wu:"Mirror slides.", skill:"1v1: stay between player and hoop. No reach-in.", game:"Protect the King with a basketball.", cd:"Feet first.", g12:"Shadow", g34:"Contest without a slap", g56:"Active" },
      { w:3,c:3, title:"3v3 half-court", focus:"Pass before a shot", wu:"Partner passing.", skill:"Must pass twice. Soft defense.", game:"Two games, rest are rebound bumpers.", cd:"Call for the ball.", g12:"3v0", g34:"3v3", g56:"4v4" },
      { w:3,c:4, title:"Switch-sides send", focus:"A hit is a new team", wu:"Foam below the waist.", skill:"Use Switch-sides from the Dodgeball page if you want a send day.", game:"Or play 3v3 again.", cd:"Walk the sideline to switch.", g12:"Roll", g34:"Underhand", g56:"Bounce-throw" },
      { w:4,c:1, title:"Weaker-hand dribble", focus:"Both hands", wu:"Left-hand taps.", skill:"Gates with the non-dominant hand.", game:"Dribble the gates, switch hands.", cd:"Head still up.", g12:"Either hand", g34:"Non-dominant", g56:"Non-dominant only" },
      { w:4,c:2, title:"Rebound and outlet", focus:"Two hands, then pass", wu:"Toss to self, catch high.", skill:"Partner shoots; other rebounds and chest-passes out.", game:"Return-line dodgeball with basketballs — catch brings a teammate in.", cd:"Chin the ball.", g12:"Teacher toss", g34:"Partner shot", g56:"Outlet on the weak side" },
      { w:4,c:3, title:"November stations", focus:"Dribble, pass, shoot, pivot", wu:"Free dribble.", skill:"Four stations × ~5 min.", game:"Teacher floats.", cd:"Hardest station?", g12:"Adult at shoot", g34:"Independent", g56:"Peer cue" },
      { w:4,c:4, title:"November festival", focus:"Celebrate the month", wu:"Easy passing.", skill:"Buffet of nest, 3v3, and wall-pass.", game:"Fitness: a dribble that lasted longer.", cd:"Thank a passer.", g12:"One game", g34:"Two", g56:"Students host" },
    ],
  },
  {
    name: "December",
    guide: "Floor hockey — stick safety, dribble, pass (three weeks if needed)",
    pew: "Movement Skill Development, Safety, Healthy Relationships",
    equipment: "Floor-hockey sticks, foam balls or soft pucks, cones, pinnies, tape goals",
    fitness: "Stick-handling count in a hoop for 20 seconds. Personal.",
    notes: "Sticks stay below the knee. No slapshots. No skating. If Advent is only three weeks, stop after Week 3 and save Week 4 for January.",
    lessons: [
      { w:1,c:1, title:"Stick on the floor", focus:"Two-hand grip, blade down", wu:"Walk with the stick — blade never above the knee.", skill:"Push a foam ball. Stop it with the blade.", game:"Hockey hurdle dribble.", cd:"Blade on the floor.", g12:"Feet-only if sticks are new", g34:"Push only", g56:"Two-touch through gates" },
      { w:1,c:2, title:"Dribble in a space", focus:"Tiny touches", wu:"Weave cones.", skill:"Forehand and a gentle backhand tap.", game:"Sharks while stick-handling.", cd:"Head up.", g12:"Wide gates", g34:"Standard", g56:"Weaker side" },
      { w:1,c:3, title:"Push-pass", focus:"Accuracy, not a slap", wu:"Partner pass on knees first.", skill:"Pass through a gate. Receiver traps with the blade.", game:"Gate hockey.", cd:"No slapshot.", g12:"Short gate", g34:"Longer", g56:"One-touch" },
      { w:1,c:4, title:"Hockey fair play", focus:"Sticks down on the whistle", wu:"Freeze with the stick still.", skill:"Class hockey promises.", game:"Hot Dog Tag, sticks away.", cd:"Sticks parked before tag.", g12:"Walk tag", g34:"Jog", g56:"Student whistle" },
      { w:2,c:1, title:"Receive and move", focus:"Trap, then dribble", wu:"Teacher pass, class trap.", skill:"Trap, three touches, pass back.", game:"Rob the Nest with sticks.", cd:"Quiet trap.", g12:"Hands may pin the ball", g34:"Blade only", g56:"One-touch" },
      { w:2,c:2, title:"Shoot to a tape goal", focus:"Low shot", wu:"Push at a wall.", skill:"One shot from a cone. Fetch from the side.", game:"Hockey pin knockdown.", cd:"Low is good.", g12:"Kick if no sticks", g34:"Push shot", g56:"Receive then shoot" },
      { w:2,c:3, title:"2v1 to a goal", focus:"Pass before a shot", wu:"Partner pass.", skill:"Two attackers, one shadow.", game:"Numbers Hockey.", cd:"Hands off the body.", g12:"No defender", g34:"Passive", g56:"Active" },
      { w:2,c:4, title:"Hockey games day", focus:"Apply the week", wu:"Free dribble.", skill:"Vote: nest, gates, or pin knockdown.", game:"Chosen game.", cd:"One safe stick.", g12:"Feet-only option", g34:"Sticks", g56:"Student refs" },
      { w:3,c:1, title:"Defend the lane", focus:"Stick on the floor, body side-on", wu:"Mirror slides.", skill:"Shadow without a hook.", game:"Protect the King with a foam puck.", cd:"No high stick.", g12:"Shadow", g34:"Contest the ball", g56:"Active" },
      { w:3,c:2, title:"Small-sided hockey", focus:"Everyone touches the ball", wu:"Dribble freeze.", skill:"3v3 to tape goals. Must pass.", game:"Rotate two games.", cd:"Call for the ball.", g12:"4v0", g34:"3v3", g56:"4v4" },
      { w:3,c:3, title:"Circle Hoop Pass closer", focus:"Cooperation if energy is high", wu:"Stick-park stretch.", skill:"If you need a non-stick day: Circle Hoop Pass or Birthday Lineup.", game:"Or a third hockey game.", cd:"Kind voices.", g12:"Hoop pass", g34:"Either", g56:"Student lead" },
      { w:3,c:4, title:"December fitness + hockey", focus:"Stillness and a recap", wu:"Shape holds.", skill:"20-second stick-handle in a hoop.", game:"Favourite December hockey game.", cd:"What felt safer this month?", g12:"Play version", g34:"Record privately", g56:"Goal for January" },
      { w:4,c:1, title:"Weaker-side handle", focus:"Both sides of the blade", wu:"Left-side taps.", skill:"Gates on the backhand.", game:"Weave relay, weaker side.", cd:"Tiny touches.", g12:"Either side", g34:"Backhand preferred", g56:"Backhand only" },
      { w:4,c:2, title:"Power play 4v2", focus:"Use extra space", wu:"Passing circle.", skill:"Four attackers, two shadows. Extra pass.", game:"Reset after a goal.", cd:"Find the open stick.", g12:"4v1", g34:"4v2", g56:"5v3" },
      { w:4,c:3, title:"December stations", focus:"Dribble, pass, shoot, defend", wu:"Free handle.", skill:"Four floor stations.", game:"Teacher floats.", cd:"Hardest?", g12:"Adult at shoot", g34:"Independent", g56:"Peer cue" },
      { w:4,c:4, title:"Showcase or early break", focus:"Celebrate", wu:"Easy push-pass.", skill:"If school is out, use Week 3’s closer. If not: hockey buffet.", game:"Student-hosted station.", cd:"Thank a partner.", g12:"One game", g34:"Two", g56:"Hosts" },
    ],
  },
  {
    name: "January",
    guide: "Floor hockey — tactics, games, inclusion · no ice",
    pew: "Movement Skill Development, Movement Tactics, Safety, Healthy Relationships, Active Living",
    equipment: "Sticks, foam balls or pucks, pinnies, cones, tape goals",
    fitness: "Redo a 20-second handle or a private shuttle after the break.",
    notes: "All January classes stay in the gym. No skating. Continue December hockey. One class may use a foam dodgeball game from the Dodgeball page.",
    lessons: [
      { w:1,c:1, title:"Back together — hockey tag", focus:"Re-entry, sticks parked", wu:"Jog, freeze.", skill:"Review blade-down. Then sticks away.", game:"Hospital Tag or Ten-Second Tag.", cd:"Soft tag.", g12:"Walk", g34:"Jog", g56:"Student hospital lead" },
      { w:1,c:2, title:"Handle review", focus:"Tiny touches after the break", wu:"Toe-taps with the blade.", skill:"Gates both sides.", game:"Hockey hurdle dribble.", cd:"Head up.", g12:"Wide", g34:"Standard", g56:"Weaker side" },
      { w:1,c:3, title:"Pass under pressure", focus:"Trap when a shadow is near", wu:"Partner pass.", skill:"3v1 keep-away.", game:"Keep-away, then a shot.", cd:"Call for it.", g12:"3v0", g34:"3v1", g56:"4v2" },
      { w:1,c:4, title:"Cross the River closer", focus:"Teamwork without sticks", wu:"Park sticks.", skill:"Three hoops per team — floor only.", game:"Cross the River.", cd:"No stacking people.", g12:"Four hoops", g34:"Three", g56:"Silent" },
      { w:2,c:1, title:"Give-and-go hockey", focus:"Pass, then cut", wu:"Pass and walk.", skill:"Pass, cut to the goal, receive.", game:"2v1 to tape.", cd:"Don’t watch your pass.", g12:"No defender", g34:"Passive", g56:"Active" },
      { w:2,c:2, title:"Shot from a pass", focus:"One-time or trap-then-shoot", wu:"Wall pass.", skill:"Receive in a hoop, shoot.", game:"Hockey pin knockdown after a pass.", cd:"Fetch from the side.", g12:"Trap then shoot", g34:"One-time allowed", g56:"Weaker side" },
      { w:2,c:3, title:"3v3 tournament", focus:"Fair teams, short games", wu:"Handle freeze.", skill:"Rotate every 3 minutes. Must pass.", game:"Sideline players are bumpers, then they play.", cd:"Everyone plays.", g12:"3v3 big goals", g34:"3v3", g56:"4v4" },
      { w:2,c:4, title:"Pulse Race or Human Knot", focus:"Cooperative brain-break", wu:"Sticks parked.", skill:"Pulse Race. Grade 3+ may choose Human Knot with consent.", game:"Then a short hockey game.", cd:"A student may say no.", g12:"Pulse only", g34:"Pulse", g56:"Knot or pulse" },
      { w:3,c:1, title:"Power play and penalty box", focus:"Inclusion, not shame", wu:"Easy pass.", skill:"A high stick = 30 seconds at the wall stretch, then back in — not a period out.", game:"3v3 with that rule.", cd:"Sticks stay low.", g12:"Teacher watches", g34:"Players call a high stick", g56:"Student refs" },
      { w:3,c:2, title:"Goalie without a pile-up", focus:"Block with the stick on the floor", wu:"Shadow in a hoop.", skill:"One goalie per team; rotate every minute. No diving on people.", game:"Small-sided with rotating keepers.", cd:"Stay on your feet.", g12:"No keeper", g34:"Rotate", g56:"Active keeper" },
      { w:3,c:3, title:"Whole-class cooperative hockey", focus:"One ball, many touches", wu:"Circle pass.", skill:"Class keeps a foam ball up with blades — drop is a restart, not an out.", game:"Then Numbers Hockey.", cd:"Quiet blades.", g12:"Hands allowed", g34:"Blades", g56:"Count a record" },
      { w:3,c:4, title:"Foam dodgeball option", focus:"Send day if you need a break from sticks", wu:"Sticks parked.", skill:"Medic or Switch-sides from the Dodgeball page.", game:"Stay-in, below the waist.", cd:"Foam only.", g12:"Roll", g34:"Underhand", g56:"Bounce-throw" },
      { w:4,c:1, title:"January stations", focus:"Handle, pass, shoot, 2v1", wu:"Free handle.", skill:"Four stations.", game:"Teacher floats.", cd:"Hardest?", g12:"Adult at shoot", g34:"Independent", g56:"Peer cue" },
      { w:4,c:2, title:"Create a set play", focus:"Plan one pass-shot", wu:"Huddle 60 seconds.", skill:"Each group shows one play.", game:"Play it in 3v3.", cd:"Everyone has a job.", g12:"Teacher helps the plan", g34:"Independent", g56:"Audible" },
      { w:4,c:3, title:"Hockey festival", focus:"Celebrate the winter block", wu:"Easy pass.", skill:"Buffet of nest, 3v3, pin knockdown.", game:"Fitness update.", cd:"What got safer?", g12:"One game", g34:"Two", g56:"Hosts" },
      { w:4,c:4, title:"Welcome-back fitness", focus:"Private check", wu:"Easy jog.", skill:"Skip, shuttle, or handle count — private.", game:"Clockwise tag.", cd:"Starting point, not a scoreboard.", g12:"Play versions", g34:"Self-count", g56:"One private goal" },
    ],
  },
  {
    name: "February",
    guide: "Rope skills · Hoop skills · Fitness update",
    pew: "Movement Skill Development, Active Living, Safety",
    equipment: "Individual ropes, one long rope, hoops (ideally 1 per student), music",
    fitness: "30-second skip is the month’s signature check. Track personal improvement, not class rank.",
    notes: "Jump Rope for Heart can live in May. February stays in the gym — rope and hoop only. No skating.",
    lessons: [
      { w:1,c:1, title:"Rope safety and rainbow", focus:"Space, turning, no whipping", wu:"Ropes stay on the floor until told. Jog around them.", skill:"Make a rainbow: swing the rope side to side, then over. Cue: turn from the wrists.", game:"Rainbow freeze — rope still on whistle.", cd:"Ropes down before anyone talks.", g12:"Two-hand rainbow", g34:"Over-the-head turn", g56:"Alternate-hand turns" },
      { w:1,c:2, title:"Two-foot jump", focus:"Jump when the rope hits the floor", wu:"Jump in place with no rope, then with a floor rope.", skill:"Self-turned two-foot jumps. Count 1–5.", game:"Jump the river (two long ropes) then individual tries.", cd:"Soft landing.", g12:"Teacher-turned long rope optional", g34:"5 in a row goal", g56:"10 in a row or jog-step" },
      { w:1,c:3, title:"Long rope", focus:"Enter, jump, exit", wu:"Run through a still long rope.", skill:"Teacher-turned rope: in, 1–3 jumps, out.", game:"School: groups wait in a line, cheer the jumper.", cd:"How do we cheer without rushing?", g12:"Run through only", g34:"1–3 jumps", g56:"Students turn for each other" },
      { w:1,c:4, title:"Rope games", focus:"Keep moving if jumping is hard", wu:"Choice: skip or rainbow.", skill:"Helicopters (low), high-low, partner turn for a jumper.", game:"Helicopter: two students sit and swing a rope in a circle on the floor; others jump it.", cd:"Tired wrists stretch.", g12:"Very low helicopter", g34:"Standard", g56:"Add a second rope if space" },
      { w:2,c:1, title:"Hoop — spin and space", focus:"Control, not just hula", wu:"Hoop on the floor, jump in and out.", skill:"Waist spin, arm spin, roll a hoop to a partner.", game:"Chicken Checkers — hoops are rest spots.", cd:"Which spin lasted?", g12:"Arm and floor hoop", g34:"Waist tries", g56:"Change direction spin" },
      { w:2,c:2, title:"Hoop locomotion", focus:"Travel with a hoop", wu:"Step through a hoop like a magic door.", skill:"Skip while rolling, or hoop around one arm while jogging.", game:"Sheepdog: roll hoops home without knocking others.", cd:"Eyes up.", g12:"Carry or roll slowly", g34:"Roll and chase", g56:"Weak-hand roll" },
      { w:2,c:3, title:"Hoop targets and tosses", focus:"Aim", wu:"Toss-catch a hoop to self.", skill:"Hoop toss to a partner, then onto a cone.", game:"Ring toss team scores.", cd:"Soft toss.", g12:"Short distance", g34:"Step back", g56:"Opposite hand" },
      { w:2,c:4, title:"Hoop creative", focus:"Shapes and pathways", wu:"Hoop as a steering wheel.", skill:"Build a body shape inside, on, or through a hoop.", game:"Museum: half pose in hoops, half gallery walk.", cd:"Control beat speed.", g12:"One hoop one shape", g34:"Two linked hoops", g56:"Group sculpture" },
      { w:3,c:1, title:"Rope and hoop stations", focus:"Choice practice", wu:"Free skip or hoop.", skill:"Four stations × ~5 min: two-foot jump, long rope, hoop roll, hoop toss.", game:"Teacher floats.", cd:"Hardest station?", g12:"Adult at long rope", g34:"Independent", g56:"Peer turners" },
      { w:3,c:2, title:"Combine rope + hoop", focus:"Sequence", wu:"Hoop jump then 3 rope jumps.", skill:"Build a 20-second combo.", game:"Show a neighbour, then try theirs.", cd:"Borrow one idea.", g12:"Teacher combo", g34:"20 seconds", g56:"32 seconds with a change of direction" },
      { w:3,c:3, title:"Partner rope", focus:"Turn for someone else", wu:"Partner high-fives.", skill:"One turns, one jumps. Trade.", game:"How many jumps as a pair?", cd:"Kind turning is a skill.", g12:"Long rope with adult", g34:"Short rope pairs", g56:"Both turn a long rope" },
      { w:3,c:4, title:"Cardio hoops", focus:"Aerobic play with a hoop", wu:"Hoop-jog around cones.", skill:"Hoop relay: roll or carry, tag the next runner.", game:"Hoop-train tag or Chicken Checkers.", cd:"Pulse check.", g12:"Walk-carry the hoop", g34:"Continuous 2 minutes", g56:"Student-led intervals" },
      { w:4,c:1, title:"Rope challenge day", focus:"Personal records", wu:"Easy rainbows.", skill:"Private: how many two-foot jumps without a miss?", game:"Long-rope school plus helicopter.", cd:"Your number stays yours.", g12:"Count attempts, not only jumps", g34:"Best of 3", g56:"Add a criss-cross try" },
      { w:4,c:2, title:"Hoop challenge day", focus:"Personal records", wu:"Spin trials.", skill:"Longest waist spin, farthest fair roll.", game:"Hoop horseshoe + island tag.", cd:"Name a hoop skill that improved.", g12:"Roll for distance", g34:"Spin and roll", g56:"Opposite-hand spin" },
      { w:4,c:3, title:"Big-group rope/hoop games", focus:"Whole class moving", wu:"Music skip.", skill:"Teach one new group game (e.g. snake rope).", game:"Snake, helicopter, hoop islands in rotation.", cd:"Safety: ropes and hoops never thrown at people.", g12:"One game", g34:"Two", g56:"Students rotate hosts" },
      { w:4,c:4, title:"February fitness update", focus:"Skip check + favourite game", wu:"30-second skip (the monthly test).", skill:"Stretch wrists, calves, shoulders.", game:"Vote rope game or hoop game.", cd:"Compare kindly to January — only with yourself.", g12:"March in place if rope is frustrating", g34:"Record skip", g56:"Set a March goal" },
    ],
  },
  {
    name: "March",
    guide: "Parachute games · Circus activities · Fitness update",
    pew: "Personal and Social Development, Movement Skill Development, Safety",
    equipment: "Parachute or large sheet, beanbags, scarves, foam balls, optional unicycle-free circus: plates, feathers, diabolos, benches",
    fitness: "Core and shoulder endurance show up in parachute work — name them.",
    notes: "No parachute? Use a king-size sheet or two blankets. Circus here means balance, toss-and-catch, and showmanship — not aerials.",
    lessons: [
      { w:1,c:1, title:"Parachute ripples and dome", focus:"Together on a count", wu:"Hands on the chute, walk in a circle.", skill:"Small ripples, big waves, mushroom/dome. Cue: lift together.", game:"Dome — step in, sit on the edge, whisper inside.", cd:"Shoulders down.", g12:"Small ripples only at first", g34:"Dome sit", g56:"Students count the lift" },
      { w:1,c:2, title:"Parachute popcorn", focus:"Force and timing", wu:"Ripple review.", skill:"Beanbags on the chute; pop them without losing the chute.", game:"Popcorn: keep 6 bags up. Then colour-pop (only red). ", cd:"Core is working — say so.", g12:"Few bags", g34:"Colour rules", g56:"Pop to a target hoop" },
      { w:1,c:3, title:"Parachute change-places", focus:"Listen for your colour or name", wu:"Walk the circle holding the chute.", skill:"Lift, call two colours, those students change places under the chute.", game:"Sharks and Dolphins with the chute shrinking .", cd:"Heads up when you run under.", g12:"Walk only under", g34:"Jog under", g56:"Three-mouse version" },
      { w:1,c:4, title:"Parachute number games", focus:"Problem-solving as a group", wu:"Numbered spots on the chute if you have them.", skill:"Make a number with bodies on the chute; or ‘all odd colours lift.’", game:"Merry-go-round walk, then freeze numbers.", cd:"Did we wait for everyone?", g12:"Teacher calls", g34:"Student callers", g56:"Silent number shapes" },
      { w:2,c:1, title:"Circus — toss and catch", focus:"Juggle prep, eyes on the object", wu:"Self-toss scarf.", skill:"Scarf, then beanbag, then two scarves. Cue: throw to a window above the head.", game:"Class juggle: how many objects in the air at once?", cd:"Drops are part of circus.", g12:"Scarves", g34:"Beanbag plus scarf", g56:"Two beanbags" },
      { w:2,c:2, title:"Circus — balance", focus:"Stillness on a small base", wu:"Flamingo holds.", skill:"Beanbag on the head, walk a line. Then one-foot on a poly spot.", game:"Museum circus: walk the tight-line (tape), freeze if the bag falls.", cd:"Eyes on a still spot.", g12:"Wide line", g34:"Tape line", g56:"Narrow tape and a stork pause" },
      { w:2,c:3, title:"Circus — roll and plate", focus:"Object control", wu:"Roll a hoop or ball on a line.", skill:"If you have spin plates or sticks, teach a safe spin. Else: hoop spin on the arm.", game:"Waiter relay: beanbag on a hoop or plate, walk it home.", cd:"Slow is circus-smart.", g12:"Hoop as tray", g34:"Beanbag on a plate", g56:"Turn a corner without a drop" },
      { w:2,c:4, title:"Circus — partner acts", focus:"Trust and timing", wu:"Mirror toss.", skill:"Partner toss 3 in a row. Then a shared balance pose.", game:"Mini acts: 20 seconds, the other half is the audience.", cd:"Applause is the cool-down.", g12:"Teacher in each pair", g34:"20-second act", g56:"30-second act with a bow" },
      { w:3,c:1, title:"Parachute + circus mix", focus:"Whole-class show", wu:"Ripples to music.", skill:"Sequence: dome, popcorn, then a toss-catch around the chute.", game:"Run the sequence twice.", cd:"Name a muscle that worked.", g12:"Two parts", g34:"Three parts", g56:"Students order the sequence" },
      { w:3,c:2, title:"Circus stations", focus:"Practice for the show", wu:"Choice scarf or flamingo.", skill:"Stations: scarves, line-walk, waiter, hoop spin, optional bench.", game:"Rotate ~5 min.", cd:"Wrists and ankles.", g12:"Four stations", g34:"All five", g56:"Peer coaches" },
      { w:3,c:3, title:"Build a circus act", focus:"Begin, middle, end", wu:"Bow practice (serious and silly).", skill:"Groups of 4: 30-second act with a start pose and a still ending.", game:"Rehearse twice.", cd:"Still endings beat messy run-offs.", g12:"Teacher helps structure", g34:"30 seconds", g56:"45 seconds plus a formation change" },
      { w:3,c:4, title:"Circus performance day", focus:"Audience skills", wu:"Quiet walk to ‘seats’ (a line).", skill:"How to watch: eyes on the act, clap at the end.", game:"Each group performs. Then a whole-class parachute finale.", cd:"Compliment a still ending.", g12:"Short acts", g34:"Full acts", g56:"Student MC" },
      { w:4,c:1, title:"Parachute fitness", focus:"Sustained lift", wu:"Walk the chute.", skill:"Timed waves (20s on, 10s off). Name shoulders and core.", game:"Popcorn under fatigue — keep form.", cd:"Why do we rest between lifts?", g12:"Shorter waves", g34:"20/10", g56:"Students time" },
      { w:4,c:2, title:"New parachute games", focus:"Student-created rules", wu:"Favourite ripple.", skill:"Groups invent a chute game with one safety rule.", game:"Play two inventions.", cd:"Fair start shout-out.", g12:"Teacher writes the rule", g34:"One new game", g56:"Two games and a referee" },
      { w:4,c:3, title:"March stations", focus:"Chute or circus choice", wu:"Free scarf.", skill:"Half chute games, half circus stations, then swap.", game:"Teacher floats.", cd:"What do you want in April gymnastics?", g12:"Shorter halves", g34:"Full swap", g56:"Host a station" },
      { w:4,c:4, title:"March fitness update", focus:"Core/shoulder check + favourite", wu:"20s chute lift or plank on knees.", skill:"Sit-and-reach and skip-30s.", game:"Vote parachute or circus closer.", cd:"One skill, one teammate.", g12:"Play check", g34:"Record", g56:"Goal for gymnastics month" },
    ],
  },
  {
    name: "April",
    guide: "Gymnastics · Fitness update",
    pew: "Movement Skill Development, Safety, Character (control over speed)",
    equipment: "Floor space, tape lines, hoops, beanbags, cones. No benches, beams, or boxes.",
    fitness: "Strength and flexibility are the gymnastics fitness update — stillness is the test.",
    notes: "Floor-only month — no gymnastics apparatus. No inversions that load the neck. Rolls stay on the floor or a mat if you happen to have one. Control beats speed. Download the gymnastics checklist from the Gymnastics page.",
    lessons: [
      { w:1,c:1, title:"Shapes: tuck, pike, straddle, stretch", focus:"Strong shapes, tight muscles", wu:"Shake, then freeze in a shape.", skill:"Four shapes on the mat. Hold 3 seconds. Name the shape.", game:"Shape museum.", cd:"Which shape felt strongest?", g12:"Tuck and stretch", g34:"All four", g56:"Add a twist shape" },
      { w:1,c:2, title:"Travel like a gymnast", focus:"Weight transfer, quiet feet", wu:"Animal travels on mats only.", skill:"Bear, crab, seal, bunny hop. Still start and still end.", game:"Traffic animals — change animal on the drum.", cd:"Quiet travel.", g12:"Two animals", g34:"Four", g56:"Students invent a fifth" },
      { w:1,c:3, title:"Balance", focus:"Small base, still eyes", wu:"Flamingo.", skill:"One-foot, scale attempts, beanbag on the head. Relevé if ready.", game:"Who can be a statue through a whole song intro?", cd:"Eyes on one spot.", g12:"Wide base OK", g34:"One-foot 5 seconds", g56:"5–8 seconds plus a change" },
      { w:1,c:4, title:"Jump and land", focus:"Bend–jump–stick", wu:"Jump the river.", skill:"Straight jump, star jump, tuck jump onto mat. Stick the landing.", game:"Lily-pad hoop jumps with a stuck landing.", cd:"Why bend?", g12:"Straight jump only", g34:"Star and tuck", g56:"Half-turn jump" },
      { w:2,c:1, title:"Log roll", focus:"Long, tight body, no head lead", wu:"Rock like a log on the back.", skill:"Log roll on the floor. Stop in a stretch shape. Space between rollers.", game:"Log-roll and freeze — quality over speed.", cd:"Dizzy = sit.", g12:"Teacher beside", g34:"Independent", g56:"Two rolls to a shape" },
      { w:2,c:2, title:"Rock and roll (not a neck roll)", focus:"Rock to shoulder-blades, not the head", wu:"Tuck rocks.", skill:"Rock back and up to sit. No diving onto the head.", game:"Rock-and-shape: rock, then freeze a shape.", cd:"Head never leads a collapse.", g12:"Rocks only", g34:"Rock to stand with help", g56:"Rock to stand" },
      { w:2,c:3, title:"Link two skills", focus:"Sequence", wu:"Shape, travel, shape.", skill:"Build: shape + roll or jump + shape.", game:"Pairs teach their link to another pair.", cd:"Share one link you liked.", g12:"Shape + travel", g34:"Three parts", g56:"Four parts with a level change" },
      { w:2,c:4, title:"April stations — travel, jump, roll, balance", focus:"Quality reps", wu:"Line walk on the floor.", skill:"Four floor stations × ~5 min: animal travel, jump-stick, log roll, flamingo.", game:"Teacher floats.", cd:"Wrists and hips.", g12:"Adult at roll", g34:"Independent", g56:"Peer safety coach" },
      { w:3,c:1, title:"Tape beam", focus:"Walk a floor line and step off", wu:"Line walks on the floor.", skill:"Walk a taped ‘beam’ or Floor rope walk. Stop, step off to a stick. One student per line.", game:"Waiting students: flamingo or shape holds.", cd:"Eyes on a wall spot.", g12:"Wide tape", g34:"Narrow tape", g56:"Pause in a stork on the line" },
      { w:3,c:2, title:"Hoop and floor pathways", focus:"Change of direction with control", wu:"Hoop step-in.", skill:"Path: hoop, log roll on the floor, hoop, stick.", game:"Follow the path in waves of 4.", cd:"Did you rush?", g12:"No roll in the path", g34:"Full path", g56:"Add a jump" },
      { w:3,c:3, title:"Partner balances (simple)", focus:"Base of support, consent", wu:"Stand back-to-back.", skill:"Only counters that both can leave instantly: palm to palm, seated lean.", game:"Statue pairs. No lifts.", cd:"You may say no to a shape.", g12:"Palm to palm only", g34:"Seated lean", g56:"Create a still pair shape" },
      { w:3,c:4, title:"Group sequence", focus:"Unison and canon", wu:"Class stretch shape.", skill:"Whole class: travel, jump, shape on a count.", game:"Perform in canon (waves).", cd:"One thing your group solved.", g12:"Unison only", g34:"Two-wave canon", g56:"Three-wave canon" },
      { w:4,c:1, title:"Build a routine", focus:"Begin, middle, still end", wu:"Favourite shape.", skill:"Individual or pair routine, 20–30 seconds.", game:"Rehearse, then gallery.", cd:"Still ending.", g12:"Two skills", g34:"Four skills", g56:"Six skills plus a level change" },
      { w:4,c:2, title:"Performance and judging kindly", focus:"Character: notice control", wu:"Audience practice.", skill:"Watch for stillness, not tricks.", game:"Perform routines. Class names one controlled moment.", cd:"Compliment a still ending.", g12:"Show one skill", g34:"Full routine", g56:"Student judges use a 3-cue rubric" },
      { w:4,c:3, title:"Gymnastics buffet", focus:"Choice", wu:"Free shapes.", skill:"Open stations from the month.", game:"Students pick two stations, then a class sequence.", cd:"What felt controlled?", g12:"Two stations", g34:"Open gym", g56:"Host" },
      { w:4,c:4, title:"April fitness update", focus:"Strength, flexibility, stillness", wu:"Shape holds 20s.", skill:"Wall sit or chair, sit-and-reach, flamingo time.", game:"Vote a gentle closer: museum or animal relay.", cd:"Control beat speed this month — say why.", g12:"Play versions", g34:"Record", g56:"Goal for May running" },
    ],
  },
  {
    name: "May",
    guide: "Volleyball (Weeks 1–2) · Track and field (Weeks 3–4) · Jump Rope for Heart if it falls this month",
    pew: "Movement Skill Development, Active Living, Safety, Healthy Relationships",
    equipment: "Trainers or beach balls, foam volleyballs, a tape net or rope, ropes, cones, foam shot or beanbags",
    fitness: "Skip check plus a personal timed run later in the month.",
    notes: "Weeks 1–2 are volleyball: catch is allowed in 1–2, bump/set progress in 3–6. Weeks 3–4 are track. Slide JR4H into a week your school actually runs it.",
    lessons: [
      { w:1,c:1, title:"Ready position and catch", focus:"Feet set, hands ready", wu:"Self-toss and catch.", skill:"Catch a beach ball or trainer. Move the feet.", game:"Newcomb — catch and throw over a rope.", cd:"Call ‘mine.’", g12:"Catch-throw", g34:"Catch then self-bump", g56:"Pass over" },
      { w:1,c:2, title:"Underhand send", focus:"Bowler step, contact the ball", wu:"Bowler steps.", skill:"Underhand serve or throw over a low rope.", game:"Hoop underhand to a target, then over the rope.", cd:"Step to the net.", g12:"Throw over", g34:"Underhand serve", g56:"Serve from farther" },
      { w:1,c:3, title:"Bump (forearm pass)", focus:"Flat platform, no swing", wu:"Show the platform.", skill:"Toss to self, bump up. Then partner toss.", game:"Keep-it-up with a beach ball.", cd:"Belly-button to the ball.", g12:"Catch if it drops", g34:"Bump preferred", g56:"Series of 3 bumps" },
      { w:1,c:4, title:"Volleyball games day", focus:"Apply the week", wu:"Partner catch.", skill:"Newcomb or keep-it-up.", game:"Four Corners Stay-In as a closer.", cd:"Kind call.", g12:"Catch-throw", g34:"Newcomb", g56:"Add a bump" },
      { w:2,c:1, title:"Set (finger pass)", focus:"Shape the ball up", wu:"Wrist and finger shape.", skill:"Toss to self, set up. Partner set.", game:"Circle set-catch.", cd:"Soft fingers.", g12:"Catch", g34:"Set-catch", g56:"Set-set" },
      { w:2,c:2, title:"Rotate and cover", focus:"Everyone plays every spot", wu:"Walk the rotation.", skill:"3-person rotation. Catch or bump.", game:"Small Newcomb, rotate every point.", cd:"No one hides in the back.", g12:"Teacher rotates", g34:"Players rotate", g56:"Call the rotation" },
      { w:2,c:3, title:"Small-sided volleyball", focus:"Send over, then ready", wu:"Partner bump.", skill:"3v3 over a rope. Catch allowed on first contact for 1–4.", game:"Two games, bumpers on the side.", cd:"Ready after you send.", g12:"Catch-throw", g34:"One bump then catch", g56:"Two contacts" },
      { w:2,c:4, title:"Volleyball festival", focus:"Close the net block", wu:"Easy keep-up.", skill:"Buffet of Newcomb and keep-it-up.", game:"Balloon keep-up station if you need a gentle closer.", cd:"Thank a caller.", g12:"Catch", g34:"Mix", g56:"Student refs" },
      { w:3,c:1, title:"Run review", focus:"Pacing and form", wu:"A-skips, high knees.", skill:"Easy / medium / quick lanes.", game:"Circle run relay or Line Tag.", cd:"What pace can you keep?", g12:"Walk-jog", g34:"Timed minute", g56:"Race pace vs sprint" },
      { w:3,c:2, title:"Sprint starts", focus:"Still, then go", wu:"Crouch without a block.", skill:"On your mark, set, whistle.", game:"Ten-Second Tag.", cd:"Eyes forward.", g12:"Standing start", g34:"Crouch", g56:"Block start if you have them" },
      { w:3,c:3, title:"Relays", focus:"Fair tag, stay in the lane", wu:"Practice the exchange.", skill:"Down-and-back, then a hoop baton.", game:"Zig-zag touch relay or Hop-the-hoops.", cd:"Pass on the right.", g12:"Walk exchange", g34:"Jog", g56:"Skip one way" },
      { w:3,c:4, title:"Jump Rope for Heart or jump review", focus:"Endurance skip or jump-stick", wu:"Rainbow rope or jump the river.", skill:"If JR4H is this week, skip stations. If not: jump review.", game:"JR4H games or Spot-jump path.", cd:"Celebrate effort.", g12:"Choice movement", g34:"Song-length", g56:"Student timers" },
      { w:4,c:1, title:"Long jump or hoop jump", focus:"Take-off and stick", wu:"Jump the river.", skill:"Two-foot or one-foot take-off into a hoop. Floor only.", game:"Lily-pad hoops.", cd:"Bend–jump–stick.", g12:"Two-foot", g34:"One-foot take-off", g56:"Measured hop with a stick" },
      { w:4,c:2, title:"Throws", focus:"Put or toss a foam shot", wu:"Shadow throw.", skill:"Beanbag or foam shot into a hoop zone. Fetch from the side.", game:"Punt to the line with foam, or hoop put.", cd:"No fetching in front of a thrower.", g12:"Underhand toss", g34:"Step-and-put", g56:"Weaker hand" },
      { w:4,c:3, title:"Mini meet", focus:"Fair starts, kind spectating", wu:"Spectator practice.", skill:"Sprint, jump, throw — everyone does all three.", game:"Ribbon for finishing, not only first.", cd:"Name someone who tried a new event.", g12:"Play meet", g34:"Simple scores", g56:"Student officials" },
      { w:4,c:4, title:"May fitness + field prep", focus:"Personal run or skip", wu:"Easy jog.", skill:"Private timed run or skip.", game:"Vote a gentle closer.", cd:"Goal for the June meet.", g12:"Play version", g34:"Record", g56:"Pace talk" },
    ],
  },
  {
    name: "June",
    guide: "Track and field — meet practice, relays, year-end festival",
    pew: "Movement Skill Development, Active Living, Character, Safety",
    equipment: "Cones, batons or hoops, foam shot or beanbags, pinnies, a simple heat sheet",
    fitness: "Final private check: skip, a short run, or a jump-stick. No class ranking.",
    notes: "Most schools have three weeks. The meet can be a class mini meet if there is no school meet. T-ball is optional in Week 3 if you want a striking closer.",
    lessons: [
      { w:1,c:1, title:"Meet rehearsal", focus:"Rotate events calmly", wu:"Build-ups.", skill:"Sprint, jump, throw stations as they will run.", game:"Practice waiting in line as part of the game.", cd:"Officials are helpers.", g12:"Two events", g34:"Three", g56:"Students official one event" },
      { w:1,c:2, title:"Relays and cheering", focus:"Fair exchange, kind noise", wu:"Practice the hand-off.", skill:"4 × gym-length.", game:"Circle run relay.", cd:"Cheer for every heat.", g12:"Walk-jog", g34:"Jog", g56:"Student starters" },
      { w:1,c:3, title:"Field events", focus:"Jump and throw quality", wu:"Dynamic legs.", skill:"Long-jump hoop and throw zone. One at a time.", game:"Spot-jump path.", cd:"Rake / wait / one at a time.", g12:"Foam and hoops", g34:"Field if dry", g56:"Official waiting line" },
      { w:1,c:4, title:"Meet day or mini meet", focus:"Do the event, support others", wu:"Class jog together.", skill:"Walk the event order.", game:"The meet.", cd:"What did you notice in someone else?", g12:"Play meet", g34:"School meet", g56:"Lead a younger heat if asked" },
      { w:2,c:1, title:"Sprint form review", focus:"Arms and eyes", wu:"A-skips.", skill:"Fast / slow lanes.", game:"Elements Sprint.", cd:"Hands up at the wall.", g12:"Walk-sprint", g34:"Lanes", g56:"Block or crouch" },
      { w:2,c:2, title:"Hurdle or hoop rhythm", focus:"One-foot lead, still finish", wu:"Step-over cones.", skill:"Low cones as hurdles — no apparatus.", game:"Hop-the-hoops relay.", cd:"Quiet land.", g12:"Step-over", g34:"Jog-over", g56:"Lead-leg talk" },
      { w:2,c:3, title:"Throws review", focus:"Safety first", wu:"Shadow.", skill:"Foam put or beanbag toss.", game:"Steal the Bacon with a foam shot.", cd:"Fetch from the side.", g12:"Underhand", g34:"Step-and-put", g56:"Both hands" },
      { w:2,c:4, title:"Second mini meet", focus:"Another chance at an event", wu:"Easy jog.", skill:"Repeat three events or let students pick two.", game:"Ribbons for trying.", cd:"Name a kind official.", g12:"Choice events", g34:"Scores", g56:"Student officials" },
      { w:3,c:1, title:"T-ball toss and catch", focus:"Optional striking closer", wu:"Self-catch.", skill:"Partner toss. Call ‘mine.’", game:"Overarm throw-and-catch.", cd:"Ready hands.", g12:"Beanbags", g34:"Foam ball", g56:"Move to the catch" },
      { w:3,c:2, title:"Base running", focus:"Run through the hoop", wu:"Jog the diamond.", skill:"Four hoops. Run through, do not stop on the hoop.", game:"Kickball-dodge if you want a hybrid.", cd:"Eyes up.", g12:"One base", g34:"Three", g56:"Four, tag up talk" },
      { w:3,c:3, title:"Year-end festival", focus:"Student choice", wu:"Class vote.", skill:"Stations from the year: soccer gate, hockey pass, volleyball keep-up, a relay.", game:"Festival.", cd:"Thank two people.", g12:"Two stations", g34:"Open", g56:"Hosts" },
      { w:3,c:4, title:"Final fitness + thank-you", focus:"Personal close", wu:"Easy walk-jog.", skill:"Private skip or run. Return sheets to students or files.", game:"Favourite game of the year.", cd:"One thing your body can do now.", g12:"Play version", g34:"Record", g56:"Write a goal for next year" },
      { w:4,c:1, title:"Rain or extra meet", focus:"If you have a fourth week", wu:"Build-ups.", skill:"Repeat a heat or a festival station.", game:"Student-hosted game.", cd:"Kind start.", g12:"Choice", g34:"Choice", g56:"Hosts" },
      { w:4,c:2, title:"Cooperative closer", focus:"Leave the gym kindly", wu:"Partner stretch.", skill:"Cross the River or Circle Hoop Pass.", game:"Chosen cooperative game.", cd:"No one left out.", g12:"Short", g34:"Full", g56:"Silent challenge" },
      { w:4,c:3, title:"Skill thank-you", focus:"Show one skill from the year", wu:"Free play in space.", skill:"Each student shows one skill. Class names the cue.", game:"Gallery.", cd:"Clap for control, not tricks.", g12:"One skill", g34:"Two", g56:"Teach a younger cue" },
      { w:4,c:4, title:"Last class", focus:"Celebrate", wu:"Easy lap.", skill:"Teacher choice from the year.", game:"Game the class loves.", cd:"Have a good summer — keep playing.", g12:"Calmer", g34:"Mix", g56:"Students pick" },
    ],
  },
];


const MONTH_GAMES = {
  September: [
    ["Hospital Tag", "", "Everyone is it. Cover the tag with a hand. Third tag = stretch hospital, then re-enter. 5 min max as a warm-up."],
    ["Hot Dog Tag", "", "Tagged player is the wiener and calls for a bun. Two classmates stand either side, all three shout, then 5-second free."],
    ["Line Tag / Pac-Man", "", "Stay on gym lines. No jumping lines. Use as the run-skill game."],
    ["Sharks and Dolphins", "", "Hoop islands. On “Shark attack!” taggers enter. Take one hoop away each round. No sitting out — extra sharks."],
    ["Captain’s Deck / Shipwreck", "", "Command game: bow, stern, port, starboard, hit the deck, attention. Skip elimination — last group does 5 jumping jacks and stays in."],
    ["Switch", "", "Four corners, one in the middle. On “Switch,” steal a corner. No pushing; first foot on the spot keeps it."],
    ["Rikki Tikki", "", "Pairs race to the middle and match called body parts. Last pair does jumping jacks next round — still playing."],
    ["Frozen Tag", "", "Arms out when frozen. One high-five frees. Keep 2–3 taggers."],
    ["Buffalo", "", "Pairs on inside/outside track, opposite ways. Music on = jog. Music off = meet and sit back-to-back. Last pair leads the next stretch."],
    ["Laps and Lines / Signals", "", "Change locomotor or level on the whistle. Daily September instant activity."],
  ],
  October: [
    ["Medic dodgeball", "", "Stay-in foam game — medic tap. See Dodgeball page."],
    ["Robin’s Nest", "", "Four hoop nests, balls in the middle. Feet only. Steal from the middle or another nest. First to 3."],
    ["Wall Soccer", "", "2–3 field players per team; everyone else is a wall-goalie. Rotate every 2–3 minutes."],
    ["Team Tag", "", "Tag team may only tag with a held ball. No throw, no walking with the ball. Tagged players join the tag team."],
    ["Chuck the Chicken", "", "Throw the chicken, run laps around your huddle while the other team lines up and passes over-under."],
    ["Skittles", "", "Knock the other team’s cone-skittles. Hits below the waist sit 10 steamboats, then back in. One fetcher in the safe zone."],
    ["End Zone Ball", "", "Roll (not throw) to your end-zone catchers. Other team intercepts. Soft foam only."],
    ["Card Sharks", "", "Relay: beanbag into a hoop to claim a card. Accuracy over speed."],
    ["Booger Ball", "", "G5–6 invasion: tag the ball-carrier, they must pass, cannot shoot on the tag. Net = 1, hoop = 2."],
  ],
  November: [
    ["FLY BACK", "", "Cross, grab a foam disc or ball from the safe zone, throw it home. Caught = collected. Dropped = goes back."],
    ["Bucket Ball", "", "Pass-only; ball-carrier frozen. Score by a catch in a hoop or bucket zone. Rotate the catcher."],
    ["Continuous Kick Ball", "", "Kick off a saucer cone. Partner on the other team replaces the ball to stop the play. Multiple runners."],
    ["Chuck the Chicken", "", "Same as October — now a throwing-accuracy closer."],
    ["Beat Ball / Beat the Ball", "", "Throw or kick, run the bases while fielders throw around the horn."],
    ["Thunderball", "", "Hit or kick through cone rows for 1–2–3 points. Defence stops it before the next row."],
    ["Clothespin Tag", "", "Steal one pin at a time from backs. Kneel to clip a stolen pin on the front (safe). Front pins stay."],
  ],
  December: [
    ["European Rhythmic Running", "", "Locomotor changes on a drum, tambourine, or chanted 8-count."],
    ["Human Bop-It", "", "Kick it, twist it, spin it, pull it, bop it — on the beat."],
    ["Video Game", "", "Play, rewind, fast-forward, pause, eject, slow-motion."],
    ["Captain’s Deck", "", "Same commands as September, now with dance levels and shapes."],
    ["Slap Rover", "", "Call a name over, slap-hand choose, chase back to the line. Use as a rhythm/style walk."],
    ["Mass Challenges", "", "Whole class: 3 slides left, jump high, freeze in a shape. End with a clap."],
    ["Magic Numbers", "", "10-10-10 or 7-7-7 of three named movements."],
  ],
  January: [
    ["Switch-sides", "", "Hit means join the other team. See Dodgeball page."],
    ["Hot Dog Tag", "", "Cooperative unfreeze. Default January tag."],
    ["Blob Tag", "", "Start with one pair linked. Tagged players join. Break blobs at 4 if the chain gets dangerous."],
    ["Tripod Tag", "", "Groups of 4: three join hands, one tags. Short rounds, switch the tagger."],
    ["Bug Tag / Dead Ant", "", "Tagged player is a bug on their back. Four classmates carry by wrists/ankles to a hoop hospital. No lifting off the ground for G1–2 — walk-escort instead."],
    ["Chicken Checkers", "", "2–4 tag pairs. Rest stand in hoops. Step in, say the name, swap. Keep people moving."],
    ["Four Corner Flags", "", "Four teams steal beanbag flags. Safe in your quadrant. No puppy-guarding the hoop."],
    ["Stones", "", "Two-team capture the beanbags. Tagged sit; a teammate links and walks you home."],
    ["Elves, Giants, Wizards", "", "Team RPS: elf beats wizard, wizard beats giant, giant beats elf. Winners chase; tagged join. No elimination."],
    ["Rescue Relay", "", "Run across, take a teammate by the hand, bring them home."],
    ["Hungry Snake", "", "Whole team stays linked. Head picks up objects, passes them back to the bag."],
    ["Keep Away", "", "4v1 or 3v1. Three completes, then switch the middle player."],
    ["End Zone Ball", "", "No running with the ball. Three completes or a catch in the end zone."],
    ["Rob the Nest (dribble)", "", "Dribble or carry one foam ball at a time back to a hoop nest."],
  ],
  February: [
    ["Chicken Checkers", "", "Hoop rest-spots during rope/hoop cardio."],
    ["Sharks and Dolphins", "", "Hoop islands after hoop-skill practice."],
    ["Switch", "", "Fast feet, hoop or poly-spot corners."],
    ["Helicopter / Snake rope", "", "Low long-rope circle. Jump or step over. G1–2: walk the snake."],
    ["Buzz Off / hoop free zones", "", "Hoops are rest. New player says “Buzz off” to take the hoop."],
    ["Rubber Band", "", "Face out from a circle, travel on signal, sprint back on the second signal."],
  ],
  March: [
    ["Sharks and Dolphins (chute)", "", "Parachute shrinks each round instead of removing hoops."],
    ["Bug Tag / Dead Ant", "", "Carry-to-hospital — circus-strong teamwork. G1–2 walk-escort."],
    ["Object Toss mixer", "", "Say a name, toss a scarf. Add objects until several are in the air."],
    ["Pip, Squeak and Wilbur", "", "Trios. Called name runs the circle, through a teammate arch, to a centre beanbag."],
    ["Mr. Clean", "", "Get rid of your two clothespins by clipping them on someone else’s back. Check in the clean hoop."],
    ["Parachute popcorn / dome / cat-and-mouse", "", "Core chute set from the month’s lessons."],
  ],
  April: [
    ["Signals / shapes", "", "Whistle changes level or shape. Gymnastics language: tuck, pike, stretch."],
    ["Body-part beanbags", "", "Move around spots. Called body part must touch the spot."],
    ["Magic Numbers", "", "3 movements × 7, done as travel-jump-shape."],
    ["Daytime / Nighttime", "", "Night = freeze in a gymnastic statue."],
    ["Switch", "", "Corners are mats. Quiet feet only."],
  ],
  May: [
    ["Buffalo", "", "Track intervals with a partner meet-up."],
    ["Around the Bases Relay", "", "Teams at each base, run the diamond."],
    ["Cone Relay", "", "Teacher calls 2-4-3-1; run the cones in that order."],
    ["Memory Relay", "", "Peek at a card pattern behind a cone wall, rebuild it at home."],
    ["Card Sharks", "", "Throw a beanbag to a hoop to collect a card — throw review."],
    ["Aces", "", "Outdoor if you can. Active war with a card master hoop. G5–6."],
    ["Four Corner Flags", "", "Orienteering-style steal with a map-optional outdoor version."],
    ["Attention Relay", "", "Numbered files. Call a number; those runners loop their team."],
  ],
  June: [
    ["Continuous Kick Ball", "", "T-ball cousin. Kick off a cone; partner replaces the ball to freeze runners."],
    ["Beat Ball", "", "Runner vs the ball around the horn."],
    ["RPS Rounders", "", "Meet in the middle, rock-paper-scissors, winner keeps the ball toward the end zone."],
    ["Thunderball", "", "Hit/kick through point-rows of cones."],
    ["Team Bowling", "", "Bowl at your own line of pins. Fetch and go again."],
    ["Barkball", "", "Hit, run to the end line, fielders tag with the ball in hand."],
    ["Chuck the Chicken", "", "Festival closer."],
    ["Squirrel’s Tail", "", "Tails + nuts in the middle. Steal a nut or a tail. Buy a tail back with two nuts. Outdoor G3–6."],
  ],
};


const GLANCE = [
  ["September", "Rules, emergency, fitness, body awareness, run/jump, Terry Fox", "16 lessons"],
  ["October", "Sending & receiving: kick / throw", "16 lessons"],
  ["November", "Catch / stop / hit · Throw Level 1", "16 lessons"],
  ["December", "Creative movement, rhythm", "12 lessons"],
  ["January", "cooperative · playground · invent games", "16 lessons"],
  ["February", "Rope skills · hoop skills", "16 lessons"],
  ["March", "Parachute · circus", "16 lessons"],
  ["April", "Gymnastics", "16 lessons"],
  ["May", "Run/jump/throw · JR4H · track · orienteering", "16 lessons"],
  ["June", "Track & field · T-ball", "12 lessons"]
];
if (typeof window !== "undefined") {
  window.PE = { months, MONTH_GAMES, GLANCE };
}
if (typeof module !== "undefined") module.exports = { months, MONTH_GAMES, GLANCE };
