/* Homepage: pick "This month" from today's date and point the G1–G6 links at
   the current month filtered to that grade band. Dates come from school-year.js;
   month summaries from months-index.js (generated by tools/build.js).
   Test another date with ?today=2026-10-05. */
(function () {
  var SY = window.SCHOOL_YEAR;
  var MONTHS = window.PE_MONTHS || [];
  if (!SY || !MONTHS.length) return;
  var cur = SY.currentMonth();
  var m = MONTHS.find(function (x) { return x.name === cur.name; }) || MONTHS[0];
  var today = new URLSearchParams(location.search).get("today");
  function href(extra) {
    var q = new URLSearchParams(extra || {});
    if (today) q.set("today", today);
    var s = q.toString();
    return m.file + (s ? "?" + s : "");
  }
  var title = document.getElementById("this-month-title");
  var guide = document.getElementById("this-month-guide");
  var note = document.getElementById("this-month-note");
  var link = document.getElementById("this-month-link");
  if (title) title.textContent = m.name + ": " + m.theme;
  if (guide) guide.textContent = SY.fill(m.guide);
  if (note) {
    if (cur.summer && cur.week && cur.week.kind === "summer") {
      note.textContent = "The school year is over — here is September so you can plan the first month back.";
      note.hidden = false;
    } else if (cur.summer) {
      note.textContent = "Summer break — here is September so you can plan the first month back.";
      note.hidden = false;
    } else note.hidden = true;
  }
  // This week: school week + month week from the PE week plan (school-year.js)
  var pw = cur.week, box0 = document.getElementById("this-month");
  if (box0 && pw && pw.month && !document.getElementById("this-week-line")) {
    var line = document.createElement("p");
    line.id = "this-week-line";
    line.className = "this-week-line" + (pw.kind === "break" ? " break" : "");
    // School-year week name (Week 5 · Football), then its month and week (September W5):
    // a week belongs to the month it starts in.
    var wk = (pw.name || "Week " + pw.schoolWeek) + " (" + pw.month + " W" + pw.w + (pw.startup ? ", start-up week" : "") + ")";
    var txt = pw.kind === "break"
      ? pw.message + " Next: " + wk + " · " + pw.range + "."
      : (pw.kind === "before" ? "First week: " : "This week: ") + wk + " · " + pw.range +
        (pw.note ? " · " + pw.note : "") + (pw.planNote ? " · " + pw.planNote : "") + (pw.today ? " · " + pw.today : "");
    line.textContent = txt;
    var g = document.getElementById("this-month-guide");
    if (g && g.parentNode) g.parentNode.insertBefore(line, g.nextSibling); else box0.appendChild(line);
  }
  if (link) { link.href = href() + (pw && pw.w ? "#week-" + pw.w : ""); link.textContent = "Open " + m.name + " →"; }
  var box = document.getElementById("this-month");
  if (box) box.setAttribute("data-month", m.name);
  document.querySelectorAll("#grade-grid a[data-grade]").forEach(function (a) {
    a.href = href({ grade: a.getAttribute("data-grade") });
  });
  document.querySelectorAll("#months a.month-card").forEach(function (a) {
    if (a.getAttribute("href") === m.file) a.classList.add("current");
  });
})();

/* What's New This Week (red box at the top of the homepage) follows the date: the
   plan whose `week` (Monday) matches the current school week from school-year.js.
   ?today=YYYY-MM-DD previews another date. */
(function () {
  var body = document.getElementById("whats-new-body");
  if (!body) return;
  function esc(s) { return String(s == null ? "" : s).replace(/[&<>"]/g, function (c) { return { "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" }[c]; }); }
  function planHTML(plan, lead) {
    var note = plan.note ? '<p class="whats-new-note">' + plan.note + "</p>" : "";
    var name = (plan.file || "").split("/").pop() || "plan.docx";
    return (lead || "") + '<p class="whats-new-title">' + plan.title + "</p>" + note +
      '<p class="whats-new-actions">' +
      '<a class="whats-new-btn" href="' + esc(plan.file) + '" download="' + esc(name) + '">Download this week\'s plan</a>' +
      '<a class="whats-new-link" href="weekly-plans.html">All weekly plans</a></p>';
  }
  var plans = (window.WEEKLY_PLANS || []).slice().sort(function (a, b) { return String(b.week || "").localeCompare(String(a.week || "")); });
  var SY = window.SCHOOL_YEAR;
  if (!plans.length) {
    body.innerHTML = '<p class="whats-new-title">No weekly plan posted yet.</p><p><a href="weekly-plans.html">See weekly plans</a></p>';
    return;
  }
  if (!SY || !SY.status) { body.innerHTML = planHTML(plans[0]); return; }
  var today = SY.todayISO();
  var st = SY.status(today);
  var pe = SY.peWeek ? SY.peWeek(today) : null;
  var week = st.week;
  if (st.kind === "break" || st.kind === "before") week = (SY.weeks || []).find(function (w) { return w.start > today; }) || null;
  if (st.kind === "summer" || !week) {
    body.innerHTML = '<p class="whats-new-title">No school this week.</p><p class="whats-new-note">' +
      esc(st.kind === "summer" ? "The " + ((SY.calendar && SY.calendar.label) || "") + " school year is over." : st.message || "") + "</p>" +
      '<p class="whats-new-actions"><a class="whats-new-link" href="weekly-plans.html">All weekly plans</a></p>';
    return;
  }
  var lead = st.kind === "break" || st.kind === "before"
    ? '<p class="whats-new-note"><strong>' + esc(st.message.replace(/ with Week \d+\.$/, ".")) + "</strong> Next week's plan:</p>" : "";
  var plan = plans.find(function (p) { return p.week === week.monday; });
  if (plan) { body.innerHTML = planHTML(plan, lead); return; }
  // School-year week name (Week 5 · Football) and its month (the month it starts in); the button opens that week.
  var where = pe && pe.month ? (pe.name || "Week " + pe.schoolWeek) + " (" + pe.month + " W" + pe.w + ")" : "";
  var monthLink = pe && pe.month ? '<a class="whats-new-btn" href="month-' + pe.month.toLowerCase() + ".html#week-" + pe.w + '">Open ' + esc(pe.month + " W" + pe.w) + "</a>" : "";
  body.innerHTML = lead + '<p class="whats-new-title">' + esc(week.range) + (where ? " · " + esc(where) : "") + "</p>" +
    '<p class="whats-new-note">No downloadable plan posted for this week yet. The month page has this week\'s lessons.' + (week.note ? " " + esc(week.note) + "." : "") + "</p>" +
    '<p class="whats-new-actions">' + monthLink + '<a class="whats-new-link" href="weekly-plans.html">All weekly plans</a></p>';
})();
