/* Generated by tools/build.js — do not edit by hand. */
window.PE_MONTHS = [
  {
    "name": "September",
    "file": "month-september.html",
    "theme": "Soccer and Football",
    "guide": "Soccer Weeks 2–3 (Terry Fox run Fri Sept 18 in Week 3) · football Weeks 4–5 (Sept 21–Oct 2)",
    "lessons": 16
  },
  {
    "name": "October",
    "file": "month-october.html",
    "theme": "Football",
    "guide": "Football (W1–W2) · parachute and circus (W3–W4)",
    "lessons": 16
  },
  {
    "name": "November",
    "file": "month-november.html",
    "theme": "Hockey",
    "guide": "Floor hockey — stick safety, dribble, pass, small-sided games",
    "lessons": 16
  },
  {
    "name": "December",
    "file": "month-december.html",
    "theme": "Games",
    "guide": "Tag, cooperative, invasion and festival games · three weeks if the calendar is short",
    "lessons": 16
  },
  {
    "name": "January",
    "file": "month-january.html",
    "theme": "Basketball",
    "guide": "Basketball (W1–W2) · scoop send/receive (W3–W4)",
    "lessons": 16
  },
  {
    "name": "February",
    "file": "month-february.html",
    "theme": "Ropes",
    "guide": "Rope skills · hoop skills · Jump Rope for Heart the week your school runs it",
    "lessons": 16
  },
  {
    "name": "March",
    "file": "month-march.html",
    "theme": "Volleyball",
    "guide": "Volleyball all four weeks · Newcomb to bump/set · send/receive games",
    "lessons": 16
  },
  {
    "name": "April",
    "file": "month-april.html",
    "theme": "Gymnastics",
    "guide": "Floor-only gymnastics · shapes, rolls, balances, jump-stick",
    "lessons": 16
  },
  {
    "name": "May",
    "file": "month-may.html",
    "theme": "Track",
    "guide": "Track and Field Day practice for Grades 4–6 · play versions for 1–2",
    "lessons": 16
  },
  {
    "name": "June",
    "file": "month-june.html",
    "theme": "Baseball",
    "guide": "W1: Track and Field Day · W2–W4: T-ball / baseball",
    "lessons": 16
  }
];
