/* Relays and floor stations, written for this playbook.
   House rules: high-five the next runner, no elimination, foam indoors.
   Floor-only: tape lines instead of benches. */
window.SKILL_MONTH_GAMES = {
  September: [
    ["Zig-zag touch relay", "", "Five cones in a zig-zag. Touch each, pick a beanbag from the last hoop, high-five the next."],
    ["Crab-bear walk relay", "", "Crab out (belly up), bear walk back (hips up). Short lane."],
    ["Hop-the-hoops relay", "", "Six hoops in a path. Hop out on the right foot, hop back on the left."]
  ],
  October: [
    ["Soccer weave relay", "", "Zig-zag cones. Small-touch dribble out, straight dribble home."],
    ["Tunnel kick knockdown", "", "Dribble a cone tunnel, one kick at a pin, dribble back."],
    ["Toe-tap hoop relay", "", "Weave to a hoop, ten toe-taps (switch feet), dribble home."]
  ],
  November: [
    ["Wall chest-pass relay", "", "Run to a hoop, three chest-passes off the wall, ball back in the hoop."],
    ["Throw-clap-catch relay", "", "At each cone: toss, clap, catch. Last hoop: high toss and catch."],
    ["Hoop underhand relay", "", "Beanbag from a hoop, underhand to a target hoop (three tries)."]
  ],
  December: [
    ["Beanbag head walk", "", "Bag on the head to a hoop. Drop it in. Airplane arms."]
  ],
  January: [
    ["Dribble the gates", "", "Four cone gates. Finger-pad bounce out and back. Head up."],
    ["Hockey hurdle dribble", "", "Push the foam ball under a line of low cones. Blade down."],
    ["Hockey pin knockdown", "", "Tunnel dribble, one push at a pin, dribble home."]
  ],
  February: [
    ["Knee-ball jumps", "", "Soft ball between the knees. Jump the lane and back. Reset if it drops."],
    ["Racquet waiter", "", "Beanbag on a racquet or hoop to a cone, then toss into a hoop."]
  ],
  March: [
    ["Balloon keep-up station", "", "Keep a balloon up with either hand — no catch. Count hits."]
  ],
  April: [
    ["Floor rope walk", "", "Walk a rope or tape line. Airplane arms. Step off to a stick."],
    ["Spot-jump path", "", "Poly spots in a zig-zag. Two-foot jump, quiet stick."]
  ],
  May: [
    ["Circle run relay", "", "Cone track. One runner at a time; high-five at home."],
    ["Punt to the line", "", "Drop-kick a foam ball toward a line. Chase, kick again, then run it home."]
  ],
  June: [
    ["Overarm throw-and-catch", "", "Throw to a hoop catcher, catcher runs it home, roles swap."]
  ]
};

window.SKILL_DETAILS = [
  { name: "Zig-zag touch relay", months: ["September","May"], purpose: "Change direction and tag the next runner fairly.",
    equipment: "5 cones and a hoop of beanbags per team.",
    setup: "Zig-zag cones, hoop at the far end.",
    play: ["One runner at a time. Touch each cone. Take one beanbag from the hoop. High-five the next.","First team with everyone home and sitting wins the round — then play again for quality."],
    g12: "Walk or jog. Fewer cones.", g34: "Jog.", g56: "Skip one way, jog back.",
    safety: "Pass on the right. No diving at the hoop." },
  { name: "Crab-bear walk relay", months: ["September","April"], purpose: "Two animal travels in a short bout.",
    equipment: "Two cones per lane.",
    setup: "8–10 m lanes.",
    play: ["Crab walk (belly up) to the far cone. Bear walk (hips up) home. High-five.","Wrists get a stretch after two rounds."],
    g12: "Very short. Knees down if wrists complain.", g34: "Full lane.", g56: "Switch which animal goes first.",
    safety: "Hips stay off the floor on the crab. Stop if wrists hurt." },
  { name: "Hop-the-hoops relay", months: ["September","February","May"], purpose: "One-foot hop with a planned landing.",
    equipment: "6 hoops per team.",
    setup: "Hoops almost touching in a line.",
    play: ["Hop on the right foot to the end. Hop on the left foot home."],
    g12: "Step if a hop is too much.", g34: "Hop both ways.", g56: "Two-foot jump out, hop back.",
    safety: "Quiet land. No pushing a hoop into the next jumper." },
  { name: "Soccer weave relay", months: ["October"], purpose: "Small-touch dribble through cones.",
    equipment: "6 cones, one foam soccer ball per team.",
    setup: "Zig-zag cones.",
    play: ["Weave out. Straight dribble home. Foot stays near the ball."],
    g12: "Wider gates.", g34: "Standard.", g56: "Weaker foot home.",
    safety: "Balls stay on the floor. No slide tackles." },
  { name: "Tunnel kick knockdown", months: ["October"], purpose: "Dribble, then one controlled kick at a pin.",
    equipment: "Cone tunnel, one pin or stacked cone, foam ball.",
    setup: "Tunnel to a wall or pin line.",
    play: ["Dribble the tunnel. One kick at the pin. Dribble home. Team keeps going until the pin is down."],
    g12: "Shorter tunnel. Kick from a line.", g34: "One kick only.", g56: "Weaker foot.",
    safety: "Fetchers wait to the side." },
  { name: "Toe-tap hoop relay", months: ["October"], purpose: "Dribble plus a still foot-skill.",
    equipment: "Cones, hoop, foam ball.",
    setup: "Weave to a hoop.",
    play: ["Weave to the hoop. Ten toe-taps, switching feet. Dribble home."],
    g12: "Five taps.", g34: "Ten taps.", g56: "Ten taps, then a sole-roll.",
    safety: "Ball stays in the hoop during taps." },
  { name: "Wall chest-pass relay", months: ["November","January"], purpose: "Step-and-push chest pass.",
    equipment: "Hoop, foam ball, wall space.",
    setup: "Hoop 2 m from a wall.",
    play: ["Run to the hoop. Three chest-passes off the wall. Ball back in the hoop. High-five."],
    g12: "Catch-bounce allowed.", g34: "Clean catch.", g56: "One bounce-pass in the three.",
    safety: "One team per wall panel." },
  { name: "Throw-clap-catch relay", months: ["November"], purpose: "Eyes on the ball after a toss.",
    equipment: "3 cones, hoop, foam ball.",
    setup: "Cones on the way to a hoop.",
    play: ["At each cone: toss, clap, catch. At the hoop: one high toss and catch. Home."],
    g12: "No clap — toss and catch only.", g34: "One clap.", g56: "Two claps at the hoop.",
    safety: "Balls stay in the lane." },
  { name: "Hoop underhand relay", months: ["November","June"], purpose: "Underhand accuracy.",
    equipment: "Beanbags, two hoops.",
    setup: "Home hoop and a target hoop.",
    play: ["Take a beanbag. Three underhand tries into the target. Leave a make. Home."],
    g12: "Short throw.", g34: "Step back after a make.", g56: "Opposite hand.",
    safety: "Throwers stay behind a line." },
  { name: "Beanbag head walk", months: ["December","April"], purpose: "Still head, airplane arms.",
    equipment: "Beanbag and a hoop per team.",
    setup: "Lane to a hoop.",
    play: ["Bag on the head. Walk to the hoop. Drop it in. Jog home without the bag."],
    g12: "Hold the bag with one finger if it slips.", g34: "No hands.", g56: "Walk backward home.",
    safety: "No running with a bag on the head." },
  { name: "Dribble the gates", months: ["January"], purpose: "Finger-pad bounce through gates.",
    equipment: "4 cone gates, foam basketball.",
    setup: "Zig-zag gates.",
    play: ["Dribble out through the gates. Straight dribble home. Head up at a wall mark."],
    g12: "Two-hand bounce-catch allowed.", g34: "Walk-dribble.", g56: "Jog; switch hands at the turn.",
    safety: "Balls stay below the waist." },
  { name: "Hockey hurdle dribble", months: ["January"], purpose: "Tiny touches, blade on the floor.",
    equipment: "Low cones as ‘hurdles,’ stick, foam ball.",
    setup: "Wavy line of low cones.",
    play: ["Push the ball under or through the cones. Blade down. No slapshot."],
    g12: "Feet-only if sticks are new.", g34: "Push-pass only.", g56: "Two-touch through each gate.",
    safety: "Sticks stay below the knee." },
  { name: "Hockey pin knockdown", months: ["January"], purpose: "One controlled shot after a dribble.",
    equipment: "Tunnel, pin, stick, foam ball.",
    setup: "Tunnel to a pin.",
    play: ["Dribble the tunnel. One push at the pin. Dribble home."],
    g12: "Kick the foam ball if no sticks.", g34: "One shot.", g56: "Receive a partner pass before the shot.",
    safety: "No high sticks. Fetch from the side." },
  { name: "Knee-ball jumps", months: ["February","May"], purpose: "Hold an object while jumping.",
    equipment: "Soft ball, two cones.",
    setup: "Short lane.",
    play: ["Ball between the knees. Jump to the cone and back. Reset if it drops."],
    g12: "Walk-squeeze.", g34: "Two-foot jumps.", g56: "Add a hoop to drop the ball into.",
    safety: "Soft balls only. Soft land." },
  { name: "Racquet waiter", months: ["February","March"], purpose: "Balance then a short toss.",
    equipment: "Racquet or hoop, beanbag, target hoop.",
    setup: "Lane to a cone and hoop.",
    play: ["Bag on the racquet or hoop to the cone. Toss into the target. Three tries."],
    g12: "Carry with two hands.", g34: "One-hand waiter.", g56: "Walk around a cone before the toss.",
    safety: "No swinging at people." },
  { name: "Balloon keep-up station", months: ["March"], purpose: "Strike without a catch.",
    equipment: "One balloon per pair.",
    setup: "Pairs in a square.",
    play: ["Hit, do not catch. Count hits. A drop restarts the count, not the player."],
    g12: "Two-hand tap.", g34: "Either hand.", g56: "Alternate hands.",
    safety: "Space between pairs." },
  { name: "Floor rope walk", months: ["April"], purpose: "Balance on a floor line — no bench.",
    equipment: "Rope or tape.",
    setup: "Wavy line on the floor.",
    play: ["Walk the line. Airplane arms. Step off to a stick landing."],
    g12: "Wide tape.", g34: "Rope.", g56: "Pause in a stork.",
    safety: "One walker per line." },
  { name: "Spot-jump path", months: ["April","May"], purpose: "Two-foot jump and stick.",
    equipment: "Poly spots.",
    setup: "Zig-zag spots.",
    play: ["Two-foot jump spot to spot. Quiet stick. Walk back."],
    g12: "Close spots.", g34: "Standard.", g56: "Add a half-turn on the last spot.",
    safety: "One jumper on a path." },
  { name: "Circle run relay", months: ["May","September"], purpose: "Sustained run and a fair tag.",
    equipment: "Cone circle.",
    setup: "Large loop, start cone.",
    play: ["One runner laps the circle. High-five. Next goes."],
    g12: "Walk-jog.", g34: "Jog.", g56: "Choose a pace they can keep.",
    safety: "Pass outside. No cutting the circle." },
  { name: "Punt to the line", months: ["May","June"], purpose: "Drop-kick a foam ball toward a zone.",
    equipment: "Foam football or playground ball, a line.",
    setup: "15–20 m to a line.",
    play: ["Drop and kick before the bounce. Chase. Kick again until it crosses. Run it home."],
    g12: "Place-kick from the ground.", g34: "Drop-kick.", g56: "Weaker foot once.",
    safety: "Foam only. Kick away from other lanes." },
  { name: "Overarm throw-and-catch", months: ["June","November"], purpose: "Overarm send and a ready catch.",
    equipment: "Foam ball, hoop.",
    setup: "Throw line and a hoop catcher.",
    play: ["Throw to the catcher in the hoop. Catcher runs the ball home. Roles swap."],
    g12: "Underhand allowed.", g34: "Overarm.", g56: "Catcher must call ‘mine.’",
    safety: "One ball in the air per lane." }
];
