/* Videos page renderer. Used in the browser (search, page filter, group-by
   toggle) and by tools/build.js to bake the no-JS copy into videos.html.
   Data: videos-data.js (window.VIDEO_INDEX, generated by tools/build.js). */
(function (root) {
  "use strict";
  function esc(s) {
    return String(s == null ? "" : s).replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
  }
  function vid(v) { return "v-" + v.key.replace(/[^A-Za-z0-9_-]/g, "-"); }
  function short(s, n) { s = String(s || ""); return s.length > n ? s.slice(0, n - 1).replace(/\s+\S*$/, "") + "…" : s; }

  function card(v, data) {
    var P = {};
    (data.pages || []).forEach(function (p) { P[p.id] = p.label; });
    var byPage = {};
    (v.refs || []).forEach(function (r) { (byPage[r.page] = byPage[r.page] || []).push(r); });
    var used = (v.pages || []).map(function (pg) {
      return '<li><span class="vd-page">' + esc(P[pg] || pg) + "</span><ul>" +
        byPage[pg].map(function (r) { return '<li><a href="' + esc(r.href) + '">' + esc(r.label) + "</a></li>"; }).join("") +
        "</ul></li>";
    }).join("");
    var hay = [v.title, v.channel, v.about, (v.games || []).join(" "), v.unit, (v.refs || []).map(function (r) { return r.label; }).join(" ")].join(" ").toLowerCase();
    var status = v.status === "broken" ? '<span class="vd-chip vd-bad">Link broken</span>' : "";
    return '<article class="gcard vd-card" id="' + vid(v) + '" data-pages="' + esc((v.pages || []).join(" ")) + '" data-hay="' + esc(hay) + '">' +
      '<div class="ghead"><h3><a href="' + esc(v.url) + '" target="_blank" rel="noopener">' + esc(v.title) + "</a></h3>" +
      (v.kind === "playlist" ? '<span class="src">Playlist</span>' : "") + "</div>" +
      '<p class="meta">' + esc(v.channel || "YouTube") + (v.months && v.months.length > 1 ? " · used in " + esc(v.months.join(", ")) : "") + " " + status + "</p>" +
      (v.about ? "<p>" + esc(short(v.about, 240)) + "</p>" : "") +
      (used ? '<div class="vd-used"><p class="vd-used-h">Used in</p><ul class="vd-refs">' + used + "</ul></div>" : "") +
      '<p class="yt"><a href="' + esc(v.url) + '" target="_blank" rel="noopener">Watch on YouTube</a></p>' +
      "</article>";
  }

  function byMonth(data) {
    var vids = data.videos || [];
    return (data.groups || []).map(function (g) {
      var list = vids.filter(function (v) { return (v.month || "") === g.id; });
      if (!list.length) return "";
      return '<section class="vd-group" id="' + (g.id ? "unit-" + g.id.toLowerCase() : "unit-any") + '">' +
        '<h2 class="vd-h">' + (g.href ? '<a href="' + esc(g.href) + '">' + esc(g.label) + "</a>" : esc(g.label)) +
        ' <span class="vd-count">' + list.length + "</span></h2>" +
        list.map(function (v) { return card(v, data); }).join("") + "</section>";
    }).join("");
  }
  function byPage(data) {
    var vids = data.videos || [];
    return (data.pages || []).map(function (p) {
      var list = vids.filter(function (v) { return (v.pages || []).indexOf(p.id) >= 0; });
      if (!list.length) return "";
      return '<section class="vd-group" id="page-' + esc(p.id) + '"><h2 class="vd-h">' + esc(p.label) +
        ' <span class="vd-count">' + list.length + "</span></h2>" +
        list.map(function (v) { return card(v, data); }).join("") + "</section>";
    }).join("");
  }

  function summary(data) {
    var vids = data.videos || [];
    var jump = (data.groups || []).filter(function (g) { return vids.some(function (v) { return (v.month || "") === g.id; }); })
      .map(function (g) { return '<a href="#' + (g.id ? "unit-" + g.id.toLowerCase() : "unit-any") + '">' + esc(g.id ? g.id.slice(0, 3) : "Any time") + "</a>"; }).join(" · ");
    var rep = (data.replacements || []).length
      ? '<details class="vd-rep"><summary>' + data.replacements.length + " video fix" + (data.replacements.length === 1 ? "" : "es") + " (replaced or removed)</summary><ul>" +
        data.replacements.map(function (r) {
          var to = r["new"] ? '<a href="' + esc(r["new"]) + '" target="_blank" rel="noopener">' + esc(r.newTitle || r["new"]) + "</a>" : "<em>removed</em>";
          return "<li><strong>" + esc(r.where) + ":</strong> " + esc(r.old) + " → " + to + (r.reason ? " — " + esc(r.reason) : "") + "</li>";
        }).join("") + "</ul></details>"
      : "";
    return '<p class="meta vd-summary"><strong>' + vids.length + " videos</strong> from " + esc(data.occurrences) + " links across the site" +
      (data.lastChecked ? " · links checked " + esc(data.lastChecked) : "") + "</p>" +
      '<p class="meta vd-jump">By month: ' + jump + "</p>" + rep;
  }

  function render(data) {
    return '<div id="vd-summary">' + summary(data) + '</div><div id="vd-list">' + byMonth(data) + "</div>";
  }
  root.VideosRender = { render: render, byMonth: byMonth, byPage: byPage };

  if (typeof document === "undefined" || !document.getElementById) return;
  function boot() {
    var data = root.VIDEO_INDEX;
    var list = document.getElementById("vd-list");
    var tools = document.getElementById("vd-tools");
    if (!data || !list || !tools) return;
    tools.hidden = false;
    var q = document.getElementById("q");
    var chips = document.getElementById("vd-page-filters");
    var count = document.getElementById("vd-count");
    var mode = "month", page = "all";
    chips.innerHTML = '<button type="button" data-page="all" class="on">All pages</button>' +
      (data.pages || []).filter(function (p) { return (data.videos || []).some(function (v) { return (v.pages || []).indexOf(p.id) >= 0; }); })
        .map(function (p) { return '<button type="button" data-page="' + esc(p.id) + '">' + esc(p.label) + "</button>"; }).join("");
    function draw() {
      list.innerHTML = mode === "page" ? byPage(data) : byMonth(data);
      apply();
    }
    function apply() {
      var term = (q.value || "").toLowerCase().trim();
      var ids = {};
      list.querySelectorAll(".vd-card").forEach(function (c) {
        var ok = (!term || c.getAttribute("data-hay").indexOf(term) >= 0) &&
          (page === "all" || (" " + c.getAttribute("data-pages") + " ").indexOf(" " + page + " ") >= 0);
        c.hidden = !ok;
        if (ok) ids[c.id] = 1;
      });
      list.querySelectorAll(".vd-group").forEach(function (s) { s.hidden = !s.querySelector(".vd-card:not([hidden])"); });
      var n = Object.keys(ids).length;
      count.textContent = (term || page !== "all") ? n + " matching video" + (n === 1 ? "" : "s") : "";
    }
    q.addEventListener("input", apply);
    chips.addEventListener("click", function (e) {
      var b = e.target.closest("button[data-page]");
      if (!b) return;
      page = b.getAttribute("data-page");
      chips.querySelectorAll("button").forEach(function (x) { x.classList.toggle("on", x === b); });
      apply();
    });
    document.getElementById("vd-mode").addEventListener("click", function (e) {
      var b = e.target.closest("button[data-mode]");
      if (!b) return;
      mode = b.getAttribute("data-mode");
      this.querySelectorAll("button").forEach(function (x) { x.classList.toggle("on", x === b); });
      draw();
    });
    var qs = new URLSearchParams(location.search);
    if (qs.get("q")) { q.value = qs.get("q"); apply(); }
  }
  if (document.readyState === "loading") document.addEventListener("DOMContentLoaded", boot);
  else boot();
})(typeof window !== "undefined" ? window : this);
